### ISSUE TITLE
Requesting action feedback for "Transport: Toggle preserve pitch in audio items when changing master playrate" (ID 40671)

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#301] opened 2020-09-05 18:29 UTC
Just a short report of this being On or Off would be super helpful, in line with OSARA reporting modification of the master playrate via actions.

Thanks in advance.

**Comment by RDMurray** [comment] 2020-09-05 20:36
This reminds me, I was thinking of implementing generic feedback for all toggle actions.  @jcsteh do you think this would be a good idea?

**Comment by jcsteh** [comment] 2020-09-06 07:20
The problem with generic feedback is that some of these toggle actions are
not simple on/off toggles. Some of them are a series of toggles for
mutually exclusive modes, with one toggle for each of the modes. The ruler
time unit format is a good example of this. I worry that the output could
be really confusing in some of these cases and may potentially make the
user believe something changed when it didn't. This is the same reason I am
reluctant to allow generic feedback for normal actions we don't support,
although admittedly, the risk of lying to the user with toggle actions is
probably much lower.

**Comment by jcsteh** [comment] 2020-09-06 07:22
Also, this is a duplicate of #266.

**Closed by jcsteh** 2020-09-06 07:22 UTC
