### ISSUE TITLE
I got no response.

### ISSUE THREAD

**Issue by kazenji** [jcsteh/osara#1059] opened 2024-04-19 19:50 UTC
Hi, I replied to the email you sent me but I have not heard back from you.
Please find attached what I wrote:
jajaja, because I didn't want to cause a problem with the person who started it, however, if you authorize it, I can work on it and improve it and complete it.
Regarding the keyboard map I am waiting for a reply thank you.

**Comment by ScottChesworth** [comment] 2024-04-19 19:54
Closing as this is a duplicate of #1053, I'll respond there in just a moment.

**Closed by ScottChesworth** 2024-04-19 19:54 UTC
