### ISSUE TITLE
When item phase is inverted, OSARA incorrectly displays take volume as -inf in its Item Parameters dialog

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#891] opened 2023-03-26 11:47 UTC
Passing along a report from @GianlucaApollaro, raised during a live Q&A.
Reproduction steps:
1. Insert some audio onto a track.
2. Select the item, and twiddle Control+Up/Control+Down to observe that the take volume reports as expected. It'll be at 0dB by default. All good.
3. With the item selected, hit Alt+P to view OSARA's Item Parameters dialog, observe that the slider and edit field associated with take volume param are both displaying expected values, then dismiss the dialog.
4. Hit Shift+F2 for Item Properties, Alt+I to check the "Invert phase" check box, then dismiss the dialog with Enter.
5. Retry Control+Up/Control+Down. Still all gravy, take volume is still reported as expected even with item phase inverted. But...
6. Hit Alt+P again for OSARA's Item Parameters dialog, and now, you'll find the slider and edit field associated with take volume param are both displaying a value of -inf. DOH!
7. Set item phase back to normal, the take volume values in our dialog also return to what's expected.

Going on my haphazard commenting out of random stuff, it seems like this line of code in reaper_osara.cpp is what keeps Control+Up/Control+Down reporting as expected when item phase is inverted:
"volume = fabs(volume);"
I couldn't figure out how to incorporate that into paramsUi.cpp though, the templating stuff in there broke my brain.

Thoughts?

**Comment by jcsteh** [comment] 2023-03-26 22:44
Ug. This is going to be really tricky to fix. I'm slightly worried it's going to require another refactor of the Parameters UI code. I've just spent half an hour on it and hit several dead ends.

The problem is that this doesn't just affect retrieving the value. We also need to flip the sign when we set the value. Otherwise, we'll uninvert the polarity when the user changes the value.

**Comment by jcsteh** [comment] 2023-03-26 22:50
Implementation notes: I first tried just fabs() on the value in ReaperObjVolParam::getValue. That's not ideal because it impacts all volumes, not just take volumes, but that should be fine. This works, but it doesn't handle setting the value. We need to know whether we need to flip the value in setValue, but we don't have that info here.

I guess we could check the raw value in setValue (by calling this->provider.getSetValue directly). However, that would impact all volumes, not just take volumes, which seems wasteful.

I next tried tweaking TakeParamProvider to specially handle D_VOL. That can't work because getSetValue needs to return a pointer to its value, but if we flip the sign, we can't return a pointer to it because our local variable will be out of scope. We can't allocate it dynamically because nothing will know to free it. I guess we could use a static variable, but that's awful.

**Comment by jcsteh** [comment] 2023-03-26 23:04
Heh, documenting my thinking made a much easier fix pop into my head. Not elegant, but less ugly than anything else.

**Closed** 2023-03-27 00:08 UTC
Labels: bug, paramsDialog, p1
