### ISSUE TITLE
Vocalization of time and tempo:

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#328] opened 2020-10-18 14:45 UTC
Hello, I ask if it is possible to add an action that vocalizes the current tempo of the piece, which would also serve to know in temporal real time the tempo changes caused by an envelope of the tempo itself.
It would also be useful to know the time changes, for example two quarters, three quarters, to know the exact moment in which this happens by pressing the new action assigned to a shortcut key.
Thank you so much for what you do for us.

**Comment by ScottChesworth** [comment] 2020-10-18 15:02
That info can already be found easily by moving to tempo markers, no? Given how crowded the keymap already is, can't say I'm keen on more assignments being taken up purely to report info that's already easily obtainable.

**Comment by TrapYanto** [comment] 2020-10-18 22:01
Hi Scott,

I believe that Ranetto's request is as follows:
read through a simple HotKey, which part of his song Reaper is playing; 
Example: If in a project we have 3 markers to jump from one part of the 
structure to the other: verse, special, chorus; it's fine that I 
position myself with the selection on one of the markers, but if I still 
have to play the song from that point on; but it is not at all useful 
when I have to know in real time, while my song is playing on which of 
the parts at that moment I am. First, second, third chorus, without 
putting the Reaper on hold.

Il 18/10/2020 17:02, ScottChesworth ha scritto:

**Comment by ScottChesworth** [comment] 2020-10-18 22:05
He specifically said tempo markers, not project markers.

**Comment by TrapYanto** [comment] 2020-10-18 22:22
I apologize, I had confused another conversation not belonging to this one.

In any case, the operation would seem the same: if I want to check the 
tempo variations while my song is playing, then in realtime it would 
certainly be more comfortable, faster and without the need to open a 
specific menu; same thing for the project markers.

Il 19/10/2020 00:05, ScottChesworth ha scritto:

**Comment by jcsteh** [comment] 2020-10-18 22:40
I'd say this is a duplicate of #179 with the added inclusion of reporting the time signature, no?

**Comment by ScottChesworth** [comment] 2020-10-18 22:45
What form would the screen reader report take? I can't think of a way to describe location-based stuff in relation to the current position in a useful level of detail that wouldn't be slower than just checking the bar number I'm at, moving to the nearest tempo/project marker in either direction and jumping back to where I was.

Realistically, the current UX isn't a million miles away from the UX of a sighted user. There's some scrolling and addition/subtraction of measures involved for them too, just like there is for us. WE can infer some immediate context from checking our location in bars/beats and/or minutes/seconds, just like they can with a glance at the ruler.

OSARA exists to level the field, not reinvent the wheel.

**Comment by ScottChesworth** [comment] 2020-10-18 22:48
Ah, apologies @jcsteh , didn't notice it was a dupe. Tbh I still think both issues are low priority here, but you're the coder. :)

**Comment by jcsteh** [comment] 2020-10-18 22:50
I'm not making any statement about priority, just wanting to eliminate duplicates.

I'm a little confused, though. Aren't we just talking about having it report the current tempo and time signature; e.g. "95 bpm 3/4"? I don't follow the bit about location-based or position relative stuff.

**Comment by ScottChesworth** [comment] 2020-10-18 22:56
I think he's after hearing a summary of tempo modification throughout the project via envelopes in relation to his current position, but could easily be wrong. Back to you @ranetto , try describing the workflow you're ideally looking for in more detail.

**Comment by ranetto** [comment] 2020-10-21 16:21
Hi Scot, so I think about these moments of my work:
I perform a taptempo and then, even before having inserted some time markers I want to listen to the value of the time:
in reaper, the current time is always written in the upper part of the window, and therefore a sighted person has the possibility to see it at any time.
It seems absurd to me that we should enter, after a taptempo, in the properties of the project to be able to see the numerical result.
Second phase of my work:
I'm at bar 20 and I add a time mark that gradually, from 100 scale to 80 at bar 30.
I would like, while reaper is in play, or stopping at bar 22, or 24, or 26, to know at that moment my gradual decrease in time to which real number it has arrived in order to decide whether to insert a subsequent point, whether to maintain this curve or other.
Currently, with osara I will never have the possibility to know the variation of time if not by adding a marker between the two of beginning and end, in fact changing the sense of the time envelope.
I want to know the time, precisely also in play or in stop between its varying and currently, it is not possible: on the contrary I am forced to move my position having to go to select a time marker before or after where I am.
Am I clear Scot?
?

**Comment by ScottChesworth** [comment] 2020-10-21 16:36
Aha, now I understand. @jcsteh are you following this, or would a summary of the desired UX be helpful?

FYI, in the interim, We can already read the project BPM at the top of the window at any time. Either object navigation with NVDA or touch cursor with JAWS will getcha there. You could also interact with the tap tempo button directly, which is right next to BPM status. If you don't want to learn more advanced screen reader functionality, in the next release of the key map which is coming very soon, you'll be able to decrease or increase project BPM with Alt+Dash and Alt+Equals respectively with spoken feedback. Ergo, a quick wiggle of those keys to change and then reset will report the project BPM. Whether that approach will accurately report during a decrease or increase between two markers, I don't know, not tested it, but perhaps those tips will serve some use for ya in the short-term.

**Comment by ranetto** [comment] 2020-10-21 16:46
Hi Scot, I still think that since the keymap is already very crowded, you might decide that some actions are available and each of us maps them if they need them in their workflow.
Yes, I know how to do it with jaws or NVDA, but I often already use the screenreader maybe to read a meter or to read where they are in the song or other.
I just think it would be a much simpler action that would make us even more similar in the way we work to the sighted.
I use reaper in the studio on a daily basis and I am very happy and especially when I manage to have a relationship with the client that is truly equal.
I mapped two actions that allow me to change the time of an increment during the play and here I dare say the new time from the last version, but what I meant is even more useful.
As for the position with respect to the new values ​​of the time it would not be important because that you can already read with osara even while reaper is playing.
Thanks always to everyone for your work and for the timely feedback to my questions.

**Comment by ScottChesworth** [comment] 2020-10-21 17:28
Dunno if we've really got the development resources for actions that are likely to be optional right now dude, but let's see if @jcsteh can find time to implement this. If he can, we'll find a home for it on the keymap.

**Comment by jcsteh** [comment] 2020-10-25 11:18
> Aha, now I understand. @jcsteh are you following this, or would a summary of the desired UX be helpful?

As I understand it, we just want an action to report the current tempo and time signature at the cursor. Unless I'm missing something, this is a duplicate of #179.

**Comment by ranetto** [comment] 2020-10-26 04:37
That's right James, that's right.

**Comment by jcsteh** [comment] 2020-10-26 18:50
Okay. Closing as a duplicate of #179. Please subscribe to that issue if you want updates on any progress there.

**Closed by jcsteh** 2020-10-26 18:50 UTC
