### ISSUE TITLE
Announces the status of only one item

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#1070] opened 2024-05-10 11:02 UTC
Good morning, now that soloing and muting for an item work well, I noticed that while the mute status for an item is announced, the solo status is not announced. Clearly as with muting, the status should be announced before other information. Thank you!

**Comment by ScottChesworth** [comment] 2024-05-10 11:15
I've already looked at this, couldn't figure out how to improve what we've already got. When you solo an item, really what's happening is that all others are muted. OSARA already reports that, and I think right now that's the best we can do because there doesn't seem to be a flag for item solo in the API. Closing because I'm fairly sure this isn't practical, if any other contributors know different of course feel free to reopen and label.

**Closed by ScottChesworth** 2024-05-10 11:15 UTC

**Comment by jcsteh** [comment] 2024-05-10 12:31
@RDMurray said in https://github.com/jcsteh/osara/issues/172#issuecomment-731728224 that this was in fact added to the API. In any case, this is a duplicate of that issue.
