### ISSUE TITLE
Action feedback for Edit: Move notes left/right one pixel

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#314] opened 2020-09-27 17:55 UTC
1. Insert a blank MIDI item, open the MIDI editor, make sure you're in piano roll view and insert a note. Any note will do.
2. Select the note and hit Alt+NumPad6 to move it one pixel right. Notice how there's no action feedback reported? I'm pretty sure that @leonardder did implement this though, going back some way.

The troublesome action is "Edit: Move notes right one pixel", ID 40182.

Thanks in advance for getting it talking again.

**Comment by jcsteh** [comment] 2020-10-25 11:36
@leonardder implemented feedback for the actions which lengthen/shorten one pixel, but not move by one pixel. So, these aren't implemented yet.

**Comment by jcsteh** [comment] 2020-10-25 23:04
Actually, this is a duplicate of #201.

**Closed by jcsteh** 2020-10-25 23:04 UTC
