### ISSUE TITLE
Sometimes NVDA can't read aloud the track

### ISSUE THREAD

**Issue by c469591** [jcsteh/osara#801] opened 2022-10-16 01:45 UTC
Hello everyone, I have another problem to report.
In fact, this problem has been there for a long time, but it's not so serious, recently I found that it has become more and more serious
Sometimes after loading some vst, after closing the fx window, the track list can't be read aloud.
Pressing the arrow keys did not respond at all, and ctrl+direction keys also did not respond.
After testing, I found that he is actually selecting different tracks or objects according to my operation, but it just can't be read aloud.
I need to press ctrl+o and then ESC to exit the dialog window before I can read aloud the track list normally.
These problems are bound to occur when loading certain plugins, the vsts I found so far are these

soothe2 (oeksound) [VST3]
Pianoteq 7 (Modartt) (5 out) [VST3i]
smartComp (sonible) [VST3]
Ozone used to be a problem sometimes, but it seems to be less frequent after the update to version 10
Ozone 10 (iZotope) [VST3]
I think this problem should be more than just the vsts I mentioned, there should be many more, but I didn't use them.
I'm not sure what these vsts have in common, thus causing the problem of not being able to read the tracks aloud.
I have also tested reaper's own native vsts and they are all working fine, no such problem.
If you don't have the above vsts for testing, I can provide them.
Thanks!

Translated with www.DeepL.com/Translator (free version)

**Comment by mattymc2** [comment] 2022-10-16 02:07
I second on this. I found this has become increasingly bad over the last couple of weeks. It does only seem to be with certain projects and I can’t find a definitive reason why it’s happening. Need to do more testing. I have had someone sited  to check the screen though, and nothing seems out of the ordinary.Sent from my iPhoneOn 16 Oct 2022, at 12:45 pm, c469591 ***@***.***> wrote:﻿
Hello everyone, I have another problem to report.
In fact, this problem has been there for a long time, but it's not so serious, recently I found that it has become more and more serious
Sometimes after loading some vst, after closing the fx window, the track list can't be read aloud.
Pressing the arrow keys did not respond at all, and ctrl+direction keys also did not respond.
After testing, I found that he is actually selecting different tracks or objects according to my operation, but it just can't be read aloud.
I need to press ctrl+o and then ESC to exit the dialog window before I can read aloud the track list normally.
These problems are bound to occur when loading certain plugins, the vsts I found so far are these
soothe2 (oeksound) [VST3]
Pianoteq 7 (Modartt) (5 out) [VST3i]
smartComp (sonible) [VST3]
Ozone used to be a problem sometimes, but it seems to be less frequent after the update to version 10
Ozone 10 (iZotope) [VST3]
I think this problem should be more than just the vsts I mentioned, there should be many more, but I didn't use them.
I'm not sure what these vsts have in common, thus causing the problem of not being able to read the tracks aloud.
I have also tested reaper's own native vsts and they are all working fine, no such problem.
If you don't have the above vsts for testing, I can provide them.
Thanks!
Translated with www.DeepL.com/Translator (free version)

**Comment by ScottChesworth** [comment] 2022-10-16 04:34
This is a bug with JUCE's accessibility implementation. I've long since reported it and it was fixed in their release branch back in maybe version 6.1.5, but the issue is still rife out in the wild. Devs typically run a few releases behind, so even though the problem is already addressed, real-world encounters are still on the increase.

Unfortunately, the recovery method you've already found is the best one I can Suggest.

If you're in touch with any JUCE developers, please start encouraging them to build on 7.0.2 as a minimum, because that version also includes important accessibility fixes for table navigation.

Side note: this is what happens when prerelease user testing gets passed over. Ugh.

**Comment by ScottChesworth** [comment] 2022-10-16 04:35
Leaving this open for now just in case any of the bigger brains have ideas on how we might be able to mitigate the issue as a temporary measure.

**Comment by mattymc2** [comment] 2022-10-16 05:06
Ugh that’s a fun one! Sent from my iPhoneOn 16 Oct 2022, at 3:35 pm, ScottChesworth ***@***.***> wrote:﻿
Leaving this open for now just in case any of the bigger brains have ideas on how we might be able to mitigate the issue as a temporary measure.

**Comment by jcsteh** [comment] 2022-10-16 06:17
@ScottChesworth, do you know what change was made in JUCE to address this? I actually don't understand the cause, so I don't have a chance of figuring out a possible workaround at this point.

**Comment by ScottChesworth** [comment] 2022-10-16 07:22
I got told the cause but not in technical terms. When a GUI closes, apparently there's a notification that should be fired to alert the screen reader to that change. JUCE isn't firing said notification in early versions after accessibility support was added, hence the screen reder thinks the FX window is still open, but there's no objects present for it to interact with anymore. Does that give you any ideas? If not, I can ask for more details. Fair warning, they tend to be pretty slow with replies.

**Comment by ScottChesworth** [comment] 2022-10-16 07:23
Just an extra thought, the fix is probably covered in more detail on JUCE's commit log.

**Comment by jcsteh** [comment] 2022-10-16 10:22
Yeah, I envisaged it would be in the commit log, but I was hoping you might know what commit so I don't have to go hunting for a needle in a haystack. :) Ah well.

I don't really understand why not firing that event would screw things up. NVDA listens to notification events globally, so even though JUCE is doing something wrong, I don't follow why it would have this impact. I'dbe interested to know whether this breaks Narrator in the same way.

**Comment by ScottChesworth** [comment] 2022-10-16 11:12
For me, it does break Narrator in the same way. JUCE devs initially struggled to reproduce it with Narrator when I first reported it, and to be fair, I've seen other people also say Narrator is impacted less, but on my machine it's always been consistent across screen readers. Even in latter versions of JUCE after the fix for closing the GUI was committed, I've seen plenty of situations where removal of the plug-in will still cause the symptoms above. Not sure whether that one's been fixed yet, all I know is I've written in about it.

**Comment by c469591** [comment] 2022-10-16 12:47
I tested it here.
Open both NVDA and Narrator.
After loading vst as I mentioned above, both of them can't read the track aloud.
But if I open Narrator after loading vst again, Narrator can read the track normally.
I wonder if we can start with osara and use some judgment to solve the bug generated by this juce?

**Comment by ScottChesworth** [comment] 2022-10-16 22:54
I've run through the previous causes of this that I'm aware of, tested plug-ins built on a variety of JUCE 6 releases, all fixed here with NVDA. Awesome!

**Comment by jcsteh** [comment] 2022-10-16 23:00
I'd like to remove this hack eventually, as it's better not to have horrible hacks like this lurking around forever. I guess we'll wait a couple of years and re-test without it or something.

**Comment by ScottChesworth** [comment] 2022-10-16 23:05
Forgot to check one scenario, and as my lack of luck would have it, that one still causes loss of focus. DOH!
1. Create a track, instantiate a relevant JUCE-based plug-in.
2. Close the FX window. Focus stays active which is new and wonderful.
3. Now delete the track that the plug-in is instantiated on. Unfortunately focus still goes bye-bye at this point.
Is there anything you can do about that, or anything else I can provide to help chase it down?

**Comment by jcsteh** [comment] 2022-10-16 23:22
I hate computers.

**Comment by mattymc2** [comment] 2022-10-16 23:25
It’s not the computers fault that Scott keeps finding ways to break them! ;)Sent from my iPhoneOn 17 Oct 2022, at 10:23 am, James Teh ***@***.***> wrote:﻿
I hate computers.

**Comment by jcsteh** [comment] 2022-10-16 23:27
I honestly don't really understand what triggers this in the first place. I looked through the JUCE commits and I see a few bits and pieces about provider disconnection and open/close events, but without knowing which exact change fixed things, it's hard to be sure what's going on. To make matters worse, we also have to deal with Windows UIAutomationCore, which is a big black box we know nothing about.

The short of it is that I don't really know what we could hook to catch the "JUCE breaks the world when you delete it" case. The current hack looks for a foreground window change, but obviously there's no window change when you delete a track and there's no event for an effect being deleted either.

**Comment by ScottChesworth** [comment] 2022-10-16 23:28
Ideally every computer would speak with the voice of @mattymc2, so we could have a single focal point for all negative feelings.

**Comment by ScottChesworth** [comment] 2022-10-16 23:29
Shall I reach out to JUCE and try to get more technical details?

**Comment by ScottChesworth** [comment] 2022-10-16 23:33
Keep the current hack in anyway @jcsteh, it works around all other scenarios I know of that break focus. Still a big UX improvement, however ugly it might be under the hood.

**Closed** 2022-10-16 23:34 UTC
Labels: helpWanted

**Comment by jcsteh** [comment] 2022-10-16 23:35
It worries me that I'm far too good at coming up with horrible hacks.

**Comment by jcsteh** [comment] 2022-10-16 23:36
You're not going to get the "1 track removed" announcement even with this hack in place. Deal with it.

**Comment by ScottChesworth** [comment] 2022-10-16 23:37
If this works, I'm gonna do a spoof lyrics rewrite on Twitter that'll override that sense of discomfort for you. Standby...
