### ISSUE TITLE
peak watcher does not report master track

### ISSUE THREAD

**Issue by dgl1984** [jcsteh/osara#165] opened 2018-05-30 02:46 UTC
Title says it all.  The peak watcher reports the master track peaking at -150.  This behavior is consistent if the master is being monitored by the first or second track.

**Comment by jcsteh** [comment] 2018-05-30 03:38
I can't reproduce this:

1. Opened a project containing audio.
2. Pressed control+shift+w.
3. In "First track", selected "master".
4. Pressed enter.
5. Pressed alt+f9. Result: -150.0 (because no audio playing)
6. Pressed space to play.
7. Pressed alt+f9. Result: In my case, -10.4, but this will obviously
differ depending on the project.

**Comment by GarthHum** [comment] 2018-05-30 07:54
Peak watcher working as expected on the Mac, 64bit Reaper, most recent OSARA, Master track vol reported.  

On 30 May 2018, at 1:38 pm, James Teh <notifications@github.com> wrote:

I can't reproduce this:

1. Opened a project containing audio.
2. Pressed control+shift+w.
3. In "First track", selected "master".
4. Pressed enter.
5. Pressed alt+f9. Result: -150.0 (because no audio playing)
6. Pressed space to play.
7. Pressed alt+f9. Result: In my case, -10.4, but this will obviously
differ depending on the project.

**Comment by GianlucaApollaro** [comment] 2018-05-30 16:29
For making it work with the master track hidden you need to have the mixer checked in the view menu. If you keep master and mixer both unchecked you will have the issue

**Comment by jcsteh** [comment] 2018-06-04 22:56
I can't reproduce this even with both mixer and master unchecked in the View menu. Peak Watcher still reports metering for master.

**Comment by ScottChesworth** [comment] 2020-11-21 19:27
Presuming resolved as I can't reproduction on current versions, plus there hasn't been any sign of activity here since a dinosaur dropped a rock on its foot. Feel free to reopen if the issue still persists @dgl1984

**Closed by ScottChesworth** 2020-11-21 19:27 UTC
