### ISSUE TITLE
store the search field of osara in the parameter list

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#911] opened 2023-06-14 10:58 UTC
Hi all, I would like to know if it was possible to insert a parameter or an action that allows the search field of osara in the list of parameters to remain filled even after closing the list itself: I'll give you an example, when I'm working on a VCF of a synth that has many parameters, to re-modify the same parameter, for example the frequency of the VCF, I always have to rewrite everything and search for it, if, as happens in the reaper action list, one could decide whether the searched word in the list of parameters could remain after closing the list itself, this would make the work less tiring and faster to modify a parameter we are working on. Thanks in advance if you want to answer me.

**Comment by ranetto** [comment] 2023-08-08 11:39
hello everyone, I wanted to know if anyone found this feature useful, it would seem to me to speed up the work a lot, what do you think? Thank you

**Comment by ranetto** [comment] 2024-03-20 12:19
good morning, as the parameters of the synths increase, with the parameters of the effects, if I am adjusting a filter of a synthesizer or a specific parameter of an effect, such as those synths that have the previous sound or the next sound as a parameter like the meldas, I would really like it if, with an option, the search field in the parameter list could store the last searched string so as not to have to retype the name of the parameter I'm looking for every time, especially when there are many parameters. What do you think about it? Would it be difficult to implement? You could see a toggle switch to disable or enable this storage - do you find this useful? Thank you!

**Comment by jcsteh** [comment] 2024-04-13 23:30
Duplicate of #571.

**Closed by jcsteh** 2024-04-13 23:30 UTC
