### ISSUE TITLE
No speech feedback when moving to loop end points

### ISSUE THREAD

**Issue by ptorpey** [jcsteh/osara#405] opened 2020-12-02 23:26 UTC
Using JAWS 2021.
 
Define the beginning and end of a loop using the Shift+Alt+Left/Right Arrow keys.
 
Now move to the beginning or end point of the loop using shift+alt+Home/End.  Note, although the new position shows up in braille there is no speech feedback to alert the user that something has happened or where the new position is.
 
Along the same lines, after performing the above steps moving to the beginning or end of a measure by hitting the Alt+Home/End keys only speaks “Alt Home” and “Alt End” rather than the new position.  Sometimes starting playback fixes this issue.  Restarting JAWS also seems to help this last issue when moving to the beginning/end of a measure.

**Comment by ScottChesworth** [comment] 2020-12-02 23:41
@jcsteh , specific actions and IDs are in #404. Apologies for practically duplicated issues, sometimes I'm too keen for my own good. :)
One thing though, So far as I know we're not providing any feedback for moving to the beginning of current measure or start of next measure. If JAWS is already reporting that, seems like one for Jim to remove from his scripts once this is implemented right?

**Comment by ptorpey** [comment] 2020-12-02 23:52
Thanks for adding these issues in a consistent format with the project.

 

I don’t know if Jim’s scripts are providing the feedback for going to the beginning and ending of measures or not.  As I indicated, the behavior is a bit flakey since it can fail after setting loop end points and moving to one of them.  But then JAWS will begin speaking these measure movements after restarting JAWS or just playing back some audio.

 

Anyway, thanks again.  I am really enjoying my experience jumping into Reaper so far.  Very well done and much less frustrating than Samplitude!

 

--Pete

**Comment by ScottChesworth** [comment] 2020-12-03 00:12
Uh oh, he used the S word. UNLEASH THE DOGS!

Oh wait, it was in our favour wasn't it. CALL OFF THE DOGS! :)

I'll shoot Jim an email and find out what part he's playing in all this.

**Comment by jcsteh** [comment] 2020-12-03 00:12
Thanks for filing this, @ptorpey. I'm closing as a duplicate of #404 because there's more technical detail there, but please don't consider this as a lack of gratitude for you taking the time to file an issue.

**Closed by jcsteh** 2020-12-03 00:12 UTC
