### ISSUE TITLE
Auto Item Navigation gets stuck

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#141] opened 2018-01-07 19:27 UTC
Hi, 

Pretty much what the subject says. In a project with multiple automation items, you can't navigate between them reliably with control cursor left and right as this project hopefully demonstrates. 

[Auto Item Demo.rpp.zip](https://github.com/jcsteh/osara/files/4944946/Auto.Item.Demo.rpp.zip)

Thanks for looking at all of these, 

Justin

**Comment by Aleskis** [comment] 2020-02-25 13:51
The automation items are really powerful to manage pieces of envelopes and easily create some kind of LFOs. Would it be possible to investigate the blocking bug while browsing and submit a bug report to Cockos if there is a problem in REAPER? Over time, this feature has been greatly enriched. It would be great to use it easily.

**Comment by ScottChesworth** [comment] 2020-02-25 14:37
In the comments of #207, @jcsteh thought this might be due to a Reaper bug. Dunno if he's had time to dig into that any deeper, but I'm hesitant to take it to Cockos without confirmation that Reaper itself is the issue (in part because I don't use the feature here, so I'd be useless at anything beyond just outlining the issue). I'm not the only means of getting stuff seen by Cockos though. If you actually use the feature @Aleskis , try your luck in the bug reports forum at https://forum.cockos.com/forumdisplay.php?f=22. Remember that hardly anybody there will be using the OSARA key map, so it's best to use action names instead of keystrokes when writing reproduction steps.

**Comment by Aleskis** [comment] 2020-02-25 14:45
I comment this ticket, because #207 is a duplicate of this one. Before posting on Cockos's forum, we need more technical information on the issue and ensure it's not a OSARA bug.

**Comment by ScottChesworth** [comment] 2020-02-25 15:23
I won't be able to shed any light on technical information, but I think I have a way to check whether it's a Reaper bug. Unfortunately it requires some sighted assistance. Hopefully, I'll be able to figure that out tonight and report back.

**Comment by ScottChesworth** [comment] 2020-02-26 00:09
Took a run at diagnosing this as promised. My plan was to run a workflow that breaks using the OSARA key map, but without OSARA placed in UserPlugins and with eyes in attendance to verify selection. Figured that would identify whether the problem still occurs without OSARA in the equation. Unfortunately the plan fell flat because - without OSARA - I couldn't figure out how to move between automation items using keystrokes. There aren't actions for that. There didn't seem to be actions for it even once I'd reactivated OSARA, so for now I'm forced to conclude that I'm not smart enough to debug this. Back to you, @jcsteh. If I can be helpful in any way, just shout.

**Closed** 2020-08-29 05:58 UTC

**Comment by jcsteh** [comment] 2020-08-29 05:59
> @jcsteh thought this might be due to a Reaper bug.

Far from being a REAPER bug, it turns out this was a bug in Jamie's brain. The fix was a tiny change in a single line of code. Sorry about that. 😳
