### ISSUE TITLE
Problem in vocal time indication going back and forth in the track with pg up and pg down

### ISSUE THREAD

**Issue by Ambro86** [jcsteh/osara#749] opened 2022-04-29 16:42 UTC
Hello. First of all, thank you for your project, and for the beauty of being able to use Reaper on both Windows and Mac in an easy and accessible way.
There is only one small problem, which if possible I would like to have it fixed.
For now I use reaper to cut videos, and then I import them into the track, move with pg up or pg down to the desired point, divide them into regions, and cut the unnecessary ones.
Setting from the view menu, Time unit for ruler, minutes seconds, or anything else that has to do with the clock time, such as hour minutes seconds, when I press page down or page up it reads me only the seconds, not communicating for example minutes or hours. Given that I have tried to set all the different options, and for example if you set minutes and seconds, he only says the seconds and when it ends the minute restarts from 1 second.
On the other hand, communicating how many minutes I have arrived would be more useful because this way I know where I am in the video. Can it be corrected?
Thanks!

**Comment by Ambro86** [comment] 2022-04-29 16:45
I add that this behavior I have encountered both using Nvda, and using Jaws for Windows, and also using VoiceOver for Mac.

**Comment by ScottChesworth** [comment] 2022-04-29 16:52
Units are reported when they change. In other words, it's expected behaviour that you won't hear information about hours or minutes when you're moving by seconds unless you cross an hour or minute threshold. If you want a full report according to the ruler format you've chosen, Control+Shift+J on Windows or Command+Shift+J will speak that information.

**Comment by Ambro86** [comment] 2022-04-29 18:09
Thanks a lot. I just tried it and it's as you say. Sorry, I didn't
know this command before.
Best wishes and congratulations on your work.

2022-04-29 18:52 GMT+02:00, ScottChesworth ***@***.***>:

**Comment by ScottChesworth** [comment] 2022-04-29 18:23
No apology needed. If you're still finding your feet there, you might wanna join the Reaper Without Peepers group to get questions answered. It's at https://groups.io/g/rwp, or you can just send a blank email to rwp+subscribe@groups.io.

**Comment by ptorpey** [comment] 2022-04-29 18:38
I replied to one of the earlier notes via Outlook, but didn't see my reply appear here.  So, here it what I tried to send:

As you know, I’ve long been a proponent of adding an option to speak the complete time when navigating.  Here is yet another user who would find such a setting useful.

The open issue is:
#613: Ability to toggle complete speaking of position on/off

I think that the problem is more prevalent with users, like the one who just requested this option as well as me, who often work in the hours/minutes/seconds format as opposed to those users who commonly work in bars/beats format.  In fact I just got confused/mislead by this once again in a project I was working on this morning.

I know that we have had lots of discussion on this and haven’t come up with the perfect solution for all circumstances, but as someone once said to me “don’t let perfection be the enemy of good enough”.

Should be relatively easy to implement and if folks don’t have to use an alternate setting they won’t have to.

--Pete

**Comment by Ambro86** [comment] 2022-04-29 18:48
Thanks Scott, I'll join the mailing list. I think torpey is right. That is, knowing the command to have the full time read is already one more thing, but it would certainly be more comfortable to hear as you go along, for example 1 minute and 2 seconds, 2 minutes and 10 seconds, etc. More than anything else because the indication of the seconds that always start from zero is useless.
But it is only a proposal, without any obligation. It could be an option to turn on or off, so those who don't want it leave things as they are.

**Comment by ScottChesworth** [comment] 2022-04-29 19:14
Temporary workaround: import this keymap file, try moving around once imported and let me know if that's doing what you want:
https://www.dropbox.com/s/5q1r7jtg5i6mkl9/Full%20reports%20for%20Page%2C%20Home%20and%20End%20keys%20%28created%20by%20Scott%29.ReaperKeyMap?dl=1
Note: I made this set of custom actions on Windows, no idea if it'll work on Mac.

**Comment by ptorpey** [comment] 2022-04-29 19:27
This feedback is a bit better with Page Up/Down except that it says “stopped” after each announcement of time.  Probably no need for that.  In addition, we still get only partial feedback when hitting other keys such as semicolon and colon to move by other amounts.

 

Also, rather than saying something like “14 min 32 sec”, we may not need the “min” and “sec” announcements.

 

For example, when I read the following with JAWS,

00:24:15

JAWS announces:

“zero twenty four sixteen”

Which is precise feedback without extra verbiage.

 

Thanks for considering this again.

 

--Pete

**Comment by Ambro86** [comment] 2022-04-29 19:30
Thanks a lot! The time is indicated just as I wanted. Then I will jealously keep the keymap!
I can confirm that the keymap works on both Windows and Mac!
Best wishes and congratulations again for everything.

**Comment by ScottChesworth** [comment] 2022-04-29 19:32
You can examine those custom actions and add others, or I'm happy to make additions if you give me a list of the keystrokes you want reporting this way. There isn't any other flexibility available with this approach though, can't do anything about the format of the reports or the transport state being reported unfortunately. Like I said, it's only a temporary workaround.

**Comment by Ambro86** [comment] 2022-04-29 19:39
OK thanks. For now I have no other requests, also because I use Reaper
to cut videos. But with this keymap I will do better in what I have to
do, because having to cut the advertising of the videos, I know more
or less after how many minutes there will be the next, and therefore I
will be able to go much faster! Thanks!

2022-04-29 21:33 GMT+02:00, ScottChesworth ***@***.***>:

**Comment by ptorpey** [comment] 2022-04-29 19:49
Thanks for the keymap.  I thought such a preference would most easily be integrated into Osara,but I hadn’t thought of tacking together some actions that already existed as you did.

 

This does give me some ideas though.  Perhaps I can write some LUA scripts (since I’m familiar with that environment) and get the results that I’m looking for.

 

--Pete

**Comment by jcsteh** [comment] 2022-04-29 23:13
I'm closing this as a duplicate of #613, where @ptorpey originally reported this.

**Closed** 2022-04-29 23:13 UTC

**Comment by ptorpey** [comment] 2022-05-01 05:13
Below is a link to a zip archive that contains a keymap file and ReaScript that will provide full position feedback for several common navigation actions.  There is also a txt file that describes the remapped shortcuts and instructions for making use of them.

 

https://www.dropbox.com/s/fiz2id39miywobw/keymap%20and%20script%20for%20speaking%20full%20positions%20when%20navigating.zip?dl=0

 

This avoids the extraneous bar/beat or hour/minutes/seconds text as well as the stopped/playing announcements in Scott’s keymap, but gives full succinct feedback for the position in either timeframe view.

 

I tried to make this work with the Apostrophe and Semicolon keys, but couldn’t avoid some of the output that came along built into the associated hotkeys from Osara.

 

If I knew how to arrange for a global hotkey from Reaper session to session, a toggle function could probably be included if the user wanted to switch back and forth between the current behavior and the behavior provided by this keymap and script.

 

Anyway, any suggestions are welcome.  I’ll share this with the wider community if people on this list don’t find any bugs and think that others might find it useful.

 

Thanks for the idea Scott!

 

--Pete

 

 

From: ***@***.*** ***@***.***> 
Sent: Friday, April 29, 2022 1:49 PM
To: 'jcsteh/osara' ***@***.***>; 'jcsteh/osara' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [jcsteh/osara] Problem in vocal time indication going back and forth in the track with pg up and pg down (Issue #749)

 

Thanks for the keymap.  I thought such a preference would most easily be integrated into Osara,but I hadn’t thought of tacking together some actions that already existed as you did.

 

This does give me some ideas though.  Perhaps I can write some LUA scripts (since I’m familiar with that environment) and get the results that I’m looking for.

 

--Pete

**Comment by ranetto** [comment] 2022-05-08 12:57
Hello everyone, I also think it would be important to have the time in minutes seconds, especially when we are working on a commercial song that requires a respectful movement in the times, one and a half minute rits, maybe three minutes and ten seconds long song and so on.

**Comment by Ambro86** [comment] 2022-05-08 14:19
Hi Ranetto, you can find an Osara Build that announces the time in minute and second. I've tried it and works perfectly. The link is this: https://github.com/jcsteh/osara/pull/752#issuecomment-1114198243

**Comment by Ambro86** [comment] 2022-10-11 07:54
Thanks a lot! The time is indicated just as I wanted. Then I will
jealously keep the keymap!
I can confirm that the keymap works on both Windows and Mac!
Best wishes and congratulations again for everything.

2022-04-29 21:27 GMT+02:00, ptorpey ***@***.***>:

**Comment by jcsteh** [comment] 2022-10-11 10:12
Am I missing something here? The option you requested - "Report full time for time movement commands" - was added some time ago now and the issue was closed as a result.

**Comment by ScottChesworth** [comment] 2022-10-11 10:17
Seems like GitHub might be acting up. I got a flood of backdated email notifications here, this being one of them.

**Comment by jcsteh** [comment] 2022-10-11 10:19
Yeah, me too, but the GitHub comment timestamp shows these as only being a couple of hours ago. I'm now thinking these are all email replies and their email server has been holding onto these until now. I did wonder where some of my email replies had disappeared to over the past few months.
