### ISSUE TITLE
Comments for the actions: OSARA: Move to next and previous transient

### ISSUE THREAD

**Issue by tbdalgaard** [jcsteh/osara#670] opened 2022-02-04 19:42 UTC
The issue here is not a bug, but unexpected behaviour. I know that @RDMurray and @jcsteh already have seen this discussion on RWP, but thought I would raise it here.

Steps to reproduce:

1. Make a track and record something. Make a pause at the beginning.
2. You now have one item. Split this item, so that you have a little of the pause in both items.
3. Select the first item, this should only contain the audio from the pause. Press the tab key.
4. Press ctrl-shift-j to hear your position on the timeline. It will probably tell you still are at the beginning of the project.
5. Now, select the second item and press ctrl-shift-j so you know where the item starts.
6. Press tab to move to the next transient. Check with ctrl-shift-j that your position has changed from that in step 5.
7. Now press ctrl-alt-a to select both items on the track.
8. Press ctrl-home to go to start of project.
9. Press tab to jump to first transient.
10. Check with ctrl-shift-j the position. You should still be at the beginning, because the first item is selected, and there is no transient in the item.

Is it possible for OSARA to skip selection of the item under the cursor, if a selection already is established, and if a selection isn't established, select the first item, but if selected item doesn't contain any transient select next item until a transient is found?

**Comment by jcsteh** [comment] 2022-02-04 22:08
I think progressively selecting subsequent items is really risky and might
lead to potential confusion. At that point, I think I'm leaning towards the
suggestion of just not messing with item selection at all and changing the
name of the action to make it clear that there needs to be an item
selection.

**Comment by tbdalgaard** [comment] 2022-02-04 23:16
Yeah, I see that too. Would it be better to change the name of the action, and let the action respect the selection? That would get the behaviour I was hoping for, and (I think) go hand in hand with the context sensitivity philosophy. But I don't know how hard this can be to change.

**Comment by jcsteh** [comment] 2022-02-05 01:07
It's easy to change in terms of the code. The problem is that users are less easy to change and there are undoubtedly users very familiar with the existing behaviour. I took the selection thing from the original custom actions which also did that, so this behaviour goes back many years.

Does it really need to select subsequent items if the first one fails? My original thinking was that we just change it to select the item at the cursor if there's no existing item selection. Sure, that doesn't solve your problem, but you can override it by just selecting all items first. This way, we don't hurt users familiar with the existing behaviour, while still supporting the use case of moving to transients in subsequent items.

**Comment by tbdalgaard** [comment] 2022-02-05 01:42
I think the best thing would be the case you described here. My problem was that the actions didn't move to next item even though I selected all items on the track. And I am perfectly fine with the behaviour where if non item is selected the item under cursor is selected by default. I just thought it would be better if OSARA could ignore this step, if there already was item selections in place before this action was triggered, since it seems to ignore selected items at the moment.

**Comment by RDMurray** [comment] 2022-02-07 11:28
I know having to select items first can trip up new users, but all other commands in reaper that work on items work the same way.  I think consistency is more important than reinforcing the false intuition that this command is based on the current track.  IMHO we should leave item selection alone and change the action names to "OSARA: Move to next/previous transient in items" or "OSARA: Move to next/previous transient in selected items".

I also think that in general OSARA should only change Reaper behaviour where it makes sense for accessibility.

**Comment by jcsteh** [comment] 2022-02-07 11:35
I honestly don'th a strong opinion either way. I wrote the actions this way because the original custom actions (not written by me) were written this way. I figured others who used these functions more than I did had a good reason for doing so. So, take this one up with @ScottChesworth.

In general, I agree we should only tweak REAPER behaviour in extenuating circumstances. However, by that logic, we shouldn't have these actions at all and should just use REAPER's builtin tab to transient, just with feedback. From what I understand, this wasn't considered sufficient. We also seek playback when moving between items. That technically isn't necessary for accessibility. The thing to remember, though, is that some things are a great deal faster/more efficient for sighted users. I think there are cases where the default behaviour just isn't efficient enough for a keyboard only user, let alone a screen reader user.

**Comment by tbdalgaard** [comment] 2022-02-07 12:15
First of all sorry for all the trouble this issue raised...

I do get why the actions are writen the way they are, but I still think they would be better if they worked more like other actions do as @RDMurray mentioned. There are buildin actions for this, but we need a few things if playback is going while moving to a transient.

the issue with the actions as they are now is the following: They will not function probably at the moment, because the item under the cursor is the only thing that gets focus. That means if the user have selected all items on a track this gets overwriten, and only the item under the edit cursor is selected. I actually thought for half an hour they worked on selected items, and not just the item under the cursor.

That makes a huge difference if you for instance record a conversation where you introduce the other part of the conversation, and later on edit this introduction part of your project.
If you later want to skip all your own ramblings, and jump straight to the first words the other person says, this is not possible unless you manually jump to the item where the person starts to speak.
If you test with my steps to reproduce from the first comment, I think it is quite obvious how easy it is to get lost, because these actions tries to work as if they work on focused track rather than selected items
The buildin actions do take account of the selected items, so this is not a problem, and I think most users can live with this change, but I hope that @ScottChesworth will share his thoughts on this.

**Comment by ScottChesworth** [comment] 2022-02-07 12:48
I'm pretty sure I wasn't active in the community or on OSARA at the time the custom actions were made. Think that was @dgl1984 and @GianlucaApollaro's work. Perhaps those chaps can chime in and explain what was inadequate about Reaper's default behaviour? Once we understand that, I think we should verify that it's still the case and tweak the UX from there. I'm with @jcsteh in that where possible, I prefer minimal deviation from Reaper's default behaviour unless there are solid reasons why the default doesn't work for screen reader users.
I'll pop a link to this issue in the retiring Key Map Consortium group, seems there's a higher chance that Derek and Gianluca will notice it if posted there.

**Comment by GianlucaApollaro** [comment] 2022-02-07 13:33
I am probably not understanding what the problem is with the action as is... All I remember is askyng Jamie to pause and than play, because reaper was very sluggish when moving to transients without that. I'll read the issue again but I don't understand why you want to select all items before tabbing. As for seeking as we move to transient it seems very usefull for a screen reader user to know where we're going. Please help me to understand what the problem is.

**Comment by GianlucaApollaro** [comment] 2022-02-07 13:42
I tried the steps that you outlined in your issue and although I was in stop the cursor was moving correctly, so I'm clearly missing something here.

**Comment by tbdalgaard** [comment] 2022-02-07 13:46
@GianlucaApollaro I can understand why the first comment got a little confusing to read, so let me try this again:

The problem is that OSARA by default selects the item under the cursor when tab or shift-tab is pressed to jump to next or previous transient. The regular Reaper actions does not select any items, but respect this if the user already did select items on the track. This means that if you use the regular actions you will jump to the next or previous transient in the selected items on the selected track. This is not the case with the OSARA actions. If you already have selected one or more items the selection will be changed, because OSARA selects item under cursor instead of just jumping and checking for item selections first.

The issue shows up if you have items where there are no transients inside. For example I have a project where I have two tracks. One where I talk, and another with another device. Because I had to edit my voice-track the items on both tracks got split into multiple items, so the content of the project would stay in sync.
If I move to the start of the project, selected the track where I don't speak and press tab, I am moved nowhere, because there is no transient in the item which OSARA selected by default.
If I select all items on selected track and press tab, I am still moved nowhere, because that selection is gone, because OSARA selects the first item under the cursor.

If I instead use the build-in actions I am moved to the spot where a transient is detected. In my particular project that is at the 7th item on the second track.
What I hope is that OSARA would allow the user to select items and when tab is pressed move to the transient regardless of which item the transient is at.
I hope this explained this a little better, if not please let me know and I will try to demonstrate this from a project.

**Comment by GianlucaApollaro** [comment] 2022-02-07 13:55
You say:
Check with ctrl-shift-j the position. You should still be at the beginning, because the first item is selected, and there is no transient in the item.
Actually, CTrlShiftJ finds me at the end of the first item, not at the beginning, so another tab jumps me where the audio starts.

**Comment by GianlucaApollaro** [comment] 2022-02-07 14:07
I found the problem and I know why it doesn't occur to me. Go to preferences-Editing behaviour, check the "treat item edges as transients" checkbox.

**Comment by RDMurray** [comment] 2022-02-07 14:08
The issue is that the current item selection is changed.  It may work as expected in some cases, but the behaviour is different to every other item based command in Reaper.  I'm just proposing that it should respect item selection, just like the built-in command.  Everything else it does is great.

**Comment by tbdalgaard** [comment] 2022-02-07 14:12
@RDMurray  Exactly, sorry that I didn't communicate this quite as good.
Do you think this can be changed without breaking too much of the OSARA code?

**Comment by GianlucaApollaro** [comment] 2022-02-07 14:16
Here's my proposition. Kill the select item thing and let the user decide. If the checkbox treat item edges as transients is checked then it won't pass the item and stay there. If it is unchecked it will get to the next transient wherever it is. So, it'll work the opposit of what it's doing now. I hope I'm making sense

**Comment by RDMurray** [comment] 2022-02-07 14:28
Sounds great to me.  Users will have to remember to make an item selection first though.  They could also use a custom action.

**Comment by tbdalgaard** [comment] 2022-02-11 09:36
Sounds good to me as well.

**Closed** 2022-02-11 10:17 UTC
Labels: needInfo
