### ISSUE TITLE
loss of focus in multimedia browser

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#1148] opened 2024-08-22 11:20 UTC
Good morning, perhaps I had already talked about this, but help me, I don't remember: when I am in the media browser, and I send to go to the default action that I have set, that is, putting the selected media on a track, the media browser loses focus, giving reaper focus on a track. Would it be possible for the focus to be maintained on the selected media and therefore I could proceed to insert a second or third without always having to reopen the media browser, with two actions, first hiding it and then reopening it? Thank you!

**Comment by jcsteh** [comment] 2024-08-24 09:05
I'm not sure if this is currently possible. @ScottChesworth might know. If not, I think this would be better dealt with in REAPER, not OSARA. It's worth noting, though, that you may have no idea that anything happened if focus doesn't move.

**Comment by jcsteh** [comment] 2024-08-24 09:07
Actually, for me, pressing enter to insert into project doesn't move focus. I'm not sure what would be different on your system. Did you let OSARA set optimal REAPER configuration?

**Comment by ScottChesworth** [comment] 2024-08-24 09:18
It's usually some combination of window size/position causes this. Post your reaper.ini file, pretty sure we can fix it.

**Comment by ranetto** [comment] 2024-08-24 14:25
Thanks Scott I'll send you my ini right away: thanks also to everyone for the interest!

**Comment by ranetto** [comment] 2024-08-24 14:29
maybe the .ini file didn't arrive I'll try again by zipping it
[REAPERINI.zip](https://github.com/user-attachments/files/16736945/REAPERINI.zip)

**Comment by jcsteh** [comment] 2024-08-24 23:40
Actually, this is a duplicate of an issue you already filed, #1072.

**Closed by jcsteh** 2024-08-24 23:40 UTC

**Comment by ScottChesworth** [comment] 2024-08-25 13:23
[FixedREAPERIni.zip](https://github.com/user-attachments/files/16740395/

**Comment by ScottChesworth** [comment] 2024-08-25 13:24
[FixedREAPERIni.zip](https://github.com/user-attachments/files/16740404/FixedREAPERIni.zip)

**Comment by ranetto** [comment] 2024-08-26 12:10
thanks I'll try it and post the results: what has been changed?

**Comment by ScottChesworth** [comment] 2024-08-27 20:32
I tweaked the X, Y, W and H positions of the Media Explorer window to match mine. I guess at some point we might wanna add sensible settings for this to OSARA optimal config, but I don't know whether the ones I'm currently using would make sense for folks with some usable vision so I haven't done that yet.

**Comment by ranetto** [comment] 2024-08-28 09:56
Thanks Scott, first of all, before testing with the new ini, I updated reaper to the latest version, and the problem no longer occurs: maybe they changed something? Thanks again in advance!

**Comment by ranetto** [comment] 2024-08-28 09:58
however if it could be added in the optimal configuration to dare to enlarge these windows it would be useful, enlarging both this and other reaper windows becomes necessary when we work with sighted customers, even the main reaper window itself, often remains a stamp and if we do not check we do not notice it and those who watch while we work together do not know what to do. What do you think? Enlarge all windows by default? Thanks!
