### ISSUE TITLE
vocalize the zoom in the piano roll

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#327] opened 2020-10-18 14:38 UTC
I wonder if it is possible to vocalize the zoom level set on plus and minus in the piano roll useful for I wonder if it is possible to vocalize the zoom level set on plus and minus in the piano roll useful for moving the notes in the grid according to the zoom level and not according to the quantization of the grid
thank you in advance for your life-changing work

**Comment by ScottChesworth** [comment] 2020-10-18 14:59
Unfortunately we don't have access to MIDI Editor zoom through the API. I've already raised it with Cockos and it's on their to-do list, but Justin did warn me that it was more of a "at some point" thing. In the interim, you can link TCP and MIDI Editor zoom.

**Comment by ranetto** [comment] 2020-10-21 17:07
Do you know if there is a way to connect the zoom of the TCP to that of the piano roll, I seemed to have found it but I can't find it anymore.

**Comment by ScottChesworth** [comment] 2020-10-21 17:56
Yep. Open the MIDI Editor, hit Applications key on Windows or go to the menu bar on Mac. You want the View menu, then "Piano roll timebase", then "Project synced". Unfortunately it's still not possible to adjust the zoom ratio with spoken feedback from inside the MIDI Editor with that option checked, but when you set the zoom in the TCP, it'll be reflected when the editor is opened.

FYI, how-to type questions are usually best posted on either RWP, WhatsApp or Discord. More people to answer, more people observing and learning by proxy.

**Comment by ranetto** [comment] 2020-10-21 18:36
Thanks Scot, in fact I did just that and called up with the function to go through, the zoom of the project from inside the piano roll.
The zoom value of the TCP is actually spoken to me, but the zoom value of the piano roll does not really change.
Do you know why?

**Comment by ScottChesworth** [comment] 2020-10-21 18:59
Hmmm, I don't know why, sorry man. Best I can do here is give Cockos a nudge, remind 'em that we're waiting for access to this via the API.

**Comment by jcsteh** [comment] 2023-02-01 08:45
Duplicate of #174.

**Closed by jcsteh** 2023-02-01 08:45 UTC
Labels: duplicate, needsReaperFix, fixRequestedFromCockos, midiEditing
