### ISSUE TITLE
Suggestions on Snapshots feature

### ISSUE THREAD

**Issue by c469591** [jcsteh/osara#532] opened 2021-05-27 11:43 UTC
Hello everyone,
I would like to suggest that OSARa can read the name of Snapshots when switching Snapshots.

When I press
When Ctrl + Alt + 7 or Ctrl + Alt + 9,
Reading
My mix Snapshots1, my mix Snapshots2
Thank you!

**Comment by jcsteh** [comment] 2021-05-27 11:45
This is a duplicate of #110. It isn't possible without changes to SWS.

**Closed by jcsteh** 2021-05-27 11:45 UTC
