### ISSUE TITLE
Is it possible to give feedback when you switch from one snapshot to another?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#468] opened 2021-01-25 19:30 UTC
Hello,
I am using snapshots in a project and I have realized that the only way to recognize the active snapshot is to enter with the action:
SWS: Open snapshots window
Is it possible that when you cycle between snapshots there may be feedback saying the name of the selected snapshot?
For example:
SWS: Recall next snapshot
Fedback:
Name: Mix 2
SWS: Recall previous snapshot
Feedback:
Name: Mix 1
A bit like what happens with markers and so on ...
Greetings!

**Comment by jcsteh** [comment] 2021-01-28 11:41
Duplicate of #110.

**Closed by jcsteh** 2021-01-28 11:41 UTC
