### ISSUE TITLE
Excess speech when selecting all notes in midi event list, and when switching through MIDI editor views

### ISSUE THREAD

**Issue by ptorpey** [jcsteh/osara#823] opened 2022-12-18 05:27 UTC
Get into the midi editor by selecting a midi item and hitting control+alt+E.

Now if one gets into the piano roll view with alt+1 and then selects all notes in the midi item by hitting control+A, Osara reports the number of notes selected.  Good so far.

If, however, one gets into the event list by hitting alt+3 and then selects all notes by hitting control+A, Osara says "1, 2, 3, ..." and continues to count each note selected.  I generally hit control to silence the extended speech that would otherwise happen in this case.  Would be good if Osara simply anounced the number of selected notes in this case as in the piano roll view.

As a side note, although the help for control+1 says "piano roll", when one transitions from another view to the piano roll view, Osara says "midi view".  Don't know if this is worth bothering with or deserves another issue.

--Pete

**Comment by ScottChesworth** [comment] 2022-12-18 09:12
> As a side note, although the help for control+1 says "piano roll", when one transitions from another view to the piano roll view, Osara says "midi view". Don't know if this is worth bothering with or deserves another issue.
> 
Looking at the speech buffer, we are reporting action states, but those reports get interrupted when the window redraws, which happens so fast that from the front end, it's like the reports didn't exist. You can hear what we'd be reporting without interruption if you switch between Alt+1 and Alt+2. I've got no clue how to shore it up, just noting the cause.
Relevant actions in MIDI Editor section:
Mode: Piano Roll, ID 40042
Mode: Drum Map, ID 40043
Mode: Event List, ID 40056
Mode: Notation, ID 40954

**Comment by ptorpey** [comment] 2022-12-18 16:24
Looking at the speech buffer, we are reporting action states, but those reports get interrupted when the window redraws, which happens so fast that from the front end, it's like the reports didn't exist. You can hear what we'd be reporting without interruption if you switch between Alt+1 and Alt+2. I've got no clue how to shore it up, just noting the cause.

[PT] Yes, I see the same here.  Switching between some of those modes speaks properly, depending on the order of the switch, and some not.  Not an easy fix when the results depend on timing on one’s system.  But at least the switch works to get into the various modes!

[PT] 

--Pete

**Comment by jcsteh** [comment] 2022-12-18 23:29
> If, however, one gets into the event list by hitting alt+3 and then selects all notes by hitting control+A, Osara says "1, 2, 3, ..." and continues to count each note selected.

I can't reproduce this with NVDA, nor can I think of any reason OSARA would do this. I'm wondering if this might be a screen reader specific issue. Would you mind testing with a different screen reader to verify?

> As a side note, although the help for control+1 says "piano roll", when one transitions from another view to the piano roll view, Osara says "midi view". Don't know if this is worth bothering with or deserves another issue.

Please file a separate issue for this. As Scott noted, there's an explanation for this one, but it needs to be dealt with separately.

**Comment by ptorpey** [comment] 2022-12-19 00:11
I can't reproduce this with NVDA, nor can I think of any reason OSARA would do this. I'm wondering if this might be a screen reader specific issue. Would you mind testing with a different screen reader to verify?

[PT] I cannot reproduce this with NVDA either.  In fact, with JAWS this problem occurs regardless of whether or not I have Jim’s JAWS scripts loaded.  If I do take the time to listen to all of the “1, 2, 3, …” to the end, JAWS finally announces how many notes are selected.  I’ll run this by Jim to see if he can bypass the default JAWS behavior for this.

As a side note, although the help for control+1 says "piano roll", when one transitions from another view to the piano roll view, Osara says "midi view". Don't know if this is worth bothering with or deserves another issue.

Please file a separate issue for this. As Scott noted, there's an explanation for this one, but it needs to be dealt with separately.

[PT] Will do.

 

Happy holidays.

 

--Pete

**Comment by jcsteh** [comment] 2022-12-19 00:22
Okay. I'm closing this, since there's nothing OSARA can do here.

**Closed by jcsteh** 2022-12-19 00:22 UTC
Labels: midiEditing
