### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by ogomez92** [jcsteh/osara#407] opened 2020-12-03 19:04 UTC
Hi!
I just downloaded Reaper on my new Mac Mini and found that Osara isn't running.
Are there any plans to support it? I can help build it, if needed. I am a developer, though I have not worked with visual studio before.

Thanks.

**Comment by jcsteh** [comment] 2020-12-03 21:42
Duplicate of #402. Please see that issue for the status.

**Closed by jcsteh** 2020-12-03 21:42 UTC
