### ISSUE TITLE
external script: output message to screen reader

### ISSUE THREAD

**Issue by Timtam** [jcsteh/osara#298] opened 2020-09-02 18:37 UTC
This one is not exactly OSARA related, but thus worth a question I hope.
I'm currently developing a ReaScript which is specifically targeting the VI community. I want to send messages to the screen readers so that they can speak something generated by my script. Since REAPER itself doesn't offer any functionality for that in their ReaScript API, I checked OSARA and how you are doing this here.
It seems you are directly targeting UIAA here, which doesn't seem to be possible from within Lua, which i'm currently using for developing my script.
So do you any easy way to send messages from within a lua script to screen readers, without adding additional requirements like screen reader libs if possible? Or do you mind adding a script API function yourself to fullfil such functionality? This would allow developers to write more accessible scripts for REAPER and actually communicate stuff to the users.
Thanks.

**Comment by jcsteh** [comment] 2020-09-02 20:35
Duplicate of #122.

**Closed by jcsteh** 2020-09-02 20:35 UTC
