### ISSUE TITLE
Surface feedback overrides reporting of automation modes in track envelopes dialog (Shift+L)

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#755] opened 2022-05-05 23:51 UTC
This problem comes from the FRCA translation. I can't tell you for the other languages.
This action opens the window correctly but the values ​​stated in the drop-down list are the volume of the track.
Track: View envelopes for current/last touched track at mouse cursor
Thanks.

**Comment by jcsteh** [comment] 2022-05-06 00:11
I don't understand the issue here. Can you provide details on what the
screen reader reports and what you expect it to report instead? Thanks.

**Comment by ScottChesworth** [comment] 2022-05-06 13:46
Maybe the automation modes don't have translation strings? That would be a Cockos thing though.

**Comment by leejul** [comment] 2022-05-06 14:12
Maybe you should try it with .po file. OSARA tells me the volume of the 
track when it should tell the modes. I don't think Cockos will be able 
to do anything with that. Each mode is replaced by the volume value of 
the track.

**Comment by ScottChesworth** [comment] 2022-05-06 14:40
Sure, I'll try that. OSARA isn't doing anything in that dialog though dude, I'm not sure how we could be causing this.

**Comment by leejul** [comment] 2022-05-06 15:07
I don't see anything other than OSARA. Also, I can confirm that I didn't 
have this problem before. On the other hand, I can't tell you from which 
version of OSARA the bug arrived. You can do the test on your side, if 
you change the volume value of the track and you go to this menu, NVDA 
will tell you the new value of the volume slider of your track. lol 
There is something to mix up there.

**Comment by ScottChesworth** [comment] 2022-05-06 15:15
Do you have Surface Feedback enabled in OSARA Config? If so, retest with that disabled and let us know whether that makes a difference.

**Comment by leejul** [comment] 2022-05-06 15:23
You got it. If it's off, no problem.

**Comment by leejul** [comment] 2022-05-06 15:26
On the other hand, it is exactly the same behavior with Reaper in English.

**Comment by ScottChesworth** [comment] 2022-05-06 18:15
Issue title updated to reflect what's going on.

**Comment by jcsteh** [comment] 2022-05-06 23:53
Duplicate of #467.

**Closed by jcsteh** 2022-05-06 23:53 UTC
Labels: bug, p1, surfaceFeedback
