### ISSUE TITLE
Requesting new OSARA action to report project BPM

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#265] opened 2020-05-01 18:26 UTC
It's possible to obtain the info by having the transport bar shown and object navving to find the BPM at the moment, but an OSARA action would decrease the amount of button bashing required.

Thanks in advance if anyone has time to tackle this.

**Comment by jcsteh** [comment] 2020-10-25 11:20
Duplicate of #179.

**Closed** 2020-10-25 11:20 UTC
