### ISSUE TITLE
precision in parameter adjustment

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#1132] opened 2024-07-05 09:24 UTC
Hi everyone, yesterday I came across a sampler that had, among other parameters, the adjustment of the loop start and also the sample start and sample end. In this case I was not able to adjust the points precisely so as to be able to make a loop without noise and without cycle interference: in this regard I ask you if it was possible to somehow make it possible to divide the increase value by 100 or decreasing the cursor that regulates the parameters of the plugins in the appropriate Osara window: this could be done via a context on the cursor or in any other way you deem appropriate. It would be very useful and I would also find it useful in the reaper stoc sampler: so I would say two adjustments, one normal as it is now and one where the increase or decrease of the cursor is one hundredth compared to the normal one. What do you think? Thanks in advance!

**Comment by ScottChesworth** [comment] 2024-07-05 10:01
Duplicate of #593

**Closed by ScottChesworth** 2024-07-05 10:01 UTC
