### ISSUE TITLE
Lags in moving be3tween notes in large MIDI items

### ISSUE THREAD

**Issue by meckito** [jcsteh/osara#105] opened 2017-02-23 13:53 UTC
In large MIDI files moving between notes is taking much of time. Here is an example big MIDI file: http://www.kunstderfuge.com/-/midi.asp?file=stravinsky_firebird_suite_(c)nakajima.mid
If you load this file as one multichannel item, open MIDI editor and start to move between notes it will be probably verry laggish. Of course usually MIDI items will have far less notes, but if someone would like to record some concert or long song using MIDI and edit it it can be somewhat problematic.

**Comment by ScottChesworth** [comment] 2020-11-22 00:05
I'm still able to reproduce this with Reaper 6.15 and OSARA pre-323. Changing direction in the MIDI editor totally hosed Reaper and NVDA lol. Marking it as high priority (at least for closer examination) because I'm not sure I've ever seen the wheels drop off OSARA quite like that before.

**Comment by jcsteh** [comment] 2020-11-23 11:58
The issue here is that there are a lot of events and there's no REAPER API function to get a MIDI event based on time, so OSARA currently walks from the beginning (if moving forward) or the end (if moving backward) searching for the note at the right position. It would be a lot faster if OSARA used a binary search algorithm, but because I kinda suck at writing such things, that's harder than it should be. :)

I'm thinking it might be worth writing a custom C++ random access iterator class that can take a MediaItem_Take and a function (like MIDI_GetNote) and return the time position. That way, we can use std::lower_bound, std::upper_bound, std::equal_range, etc. algorithms. However, writing the custom iterator might be harder than just writing a binary search manually; I'm not sure, since I've never written a custom iterator.

**Closed** 2021-11-16 21:30 UTC
Labels: p1, midiEditing
