### ISSUE TITLE
Create an alternative interface to change effect channels on a track.

### ISSUE THREAD

**Issue by Aleskis** [jcsteh/osara#767] opened 2022-06-11 17:36 UTC
Anyone who has ever tried to change the routing of an effect on a track knows what an ordeal this is. For example, to route an effect on channels 3-4, you have to open a context menu, choose a submenu, check input 3, the sub-menu closes, you have to open it again, check input 4, the sub-menu closes... Then start again for output 3, output 4, with each time the sub-menu closes. And finally, uncheck 1-2 in input and output. This is for a single effect. If you want to do a slightly complex routing on three or four effects, you multiply the difficulty by three or four.

As with the peak watcher, we would benefit from having a custom interface that would make it easier to handle the channels. We could imagine an interface with input channels separated from output channels by a tab. In each of these panes, it would be enough to move with the arrows and check or uncheck the desired channels.

**Comment by ptorpey** [comment] 2022-10-11 09:03
I’ve never used this interface, but could this type of issue get passed along to cockos?  Seems like a dialog shouldn’t automatically close if a checkable item is checked or unchecked.  Generally hitting space would check and uncheck an item, but maybe this interferes with the play/stop function of Reaper.  Seems there could be another solution if the interface of the original UI were tweaked a bit.

 

--Pete

**Comment by Aleskis** [comment] 2023-01-03 12:55
Absolutely @ptorpey . I agree with the idea that if it can be fixed in REAPER, it's better than doing it via OSARA.
There is work going on in the I.O window in terms of accessibility:
"+ Track routing menu: improve keyboard navigation/screen reader behavior for sends
  + Track routing menu: improve screen reader behavior for hardware output list".

Wouldn't it be a good time to ask that this menu doesn't close each time we press enter? What do you think @ScottChesworth  ?

**Comment by ScottChesworth** [comment] 2023-01-03 13:58
I can raise it with Cockos while these tweaks are still in testing, but the only menu class they've currently got doesn't (and so far as I know can't) behave how you've described. Nevertheless, I'll chat with Justin about it, see if we can cook up some sort of improvement.

**Comment by ScottChesworth** [comment] 2023-01-04 16:28
> Wouldn't it be a good time to ask that this menu doesn't close each time we press enter?
> 
As I suspected, it's not possible with the current menus. Instead, I've asked them to look into implementing accessibility for the routing matrix. Got confirmation that it'll be investigated, but please keep in mind this is gonna be a big chunk of work, it might take a while to happen. I'll follow up from time to time.

**Comment by Lo-lo78** [comment] 2023-03-16 10:30
you might suggest creating a dialog like the one for envelopes.
A great job was done in that situation.

**Comment by Aleskis** [comment] 2023-03-16 12:04
By the way, this question about the setting of the effect channels will soon be central, if we don't want to miss a big new feature: the FX container:
https://forum.cockos.com/showthread.php?t=276772

**Comment by ScottChesworth** [comment] 2023-03-16 14:26
Firefox worked here. Dunno what happened there, but glad you got the registration done.

**Comment by jcsteh** [comment] 2024-05-08 10:39
This looks like a duplicate of #114. Closing. Please reopen if you believe I'm incorrect and explain what is different about this request. Thanks.

**Closed by jcsteh** 2024-05-08 10:39 UTC
Labels: needsReaperFix, fixRequestedFromCockos
