### ISSUE TITLE
Pageupp and Pagedown in midi view

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#412] opened 2020-12-06 14:41 UTC
Hello everyone, I really appreciated the check that James created in the osara menu to ensure that the playback cursor is aligned and therefore that you can scroll with pageupp and pagedown starting from the playback point.
Unfortunately in the midiview this does not work and the two commands described above do different things if you have selected some notes or if you have not selected anything and in any case they do not move the playback while you are playing a part.
James is it possible to make pageupp and pagedown behave the same as they do in TCP when you checked the box for this in the osara configuration?

**Comment by ScottChesworth** [comment] 2020-12-06 20:10
For clarity, I think @ranetto is talking about the MIDI Event List. The "Move relative to the play cursor for time movement commands during playback" setting already works fine in piano roll, and actually works fine in the Event List too, but the keymap needs to be tweaked to reflect that because our current assignments are using Cockos' movement commands, which inexplicably don't seek playback.
Short-term local fix for ya, assign PageUp and PageDown to the "Misc: Pass through key to main window" action in the MIDI Events List Editor category of your actions list.
I'll leave this issue open to remind me to do it in the OSARA keymap when time permits.
The reassigning bit takes all of 10 seconds, but the Git bit may take me a little longer lol.

**Comment by ranetto** [comment] 2020-12-07 14:28
Hi Scott, no I wanted to say that even in the midi view, that is in the piano roll, when I am playing the pageupp and pagedown do not move me as in the TCP, on the contrary they absolutely do not move the play cursor, but they play if there are notes midi previously selected, and if there are none they do not play anything but in any case they do not move the playback slider forward or backward while reaper is playing.
Does it happen to you too?

**Comment by ScottChesworth** [comment] 2020-12-07 16:12
I don't think that's what I'm seeing here, no. Can you grab the latest snapshot of OSARA and make another recording for us?

**Comment by ranetto** [comment] 2020-12-07 16:27
Of course Scott, already apologizing for my English, but by now you know unfortunately it is!

**Comment by leonardder** [comment] 2020-12-09 18:41
I can't reproduce this either, if I start playing in the midi view and use page up/down to move, it starts moving from the play cursor.
However, the chord navigation keys (left/right arrow) don't work this way and I think it can be expected that they do.

**Comment by ranetto** [comment] 2020-12-10 12:33
[midi view.zip](https://github.com/jcsteh/osara/files/5672688/midi.view.zip)
Hi Scott and everyone, here is my recording of the behavior in midi view then piano roll:
Thanks in advance!

**Comment by ranetto** [comment] 2020-12-12 15:13
Hi Scott, I just wanted to know if you understood my voice note and if you or others understood why this is happening.
Thank you so much.

**Comment by ScottChesworth** [comment] 2020-12-12 17:44
Sorry man, haven't had time to listen and figure it out yet. I've been moving this week, it's temporarily taken over my whole life lol. Will get to it asap.

**Comment by jcsteh** [comment] 2020-12-13 21:59
If you activate OSARA input help (f12) in the MIDI editor and press page up, what gets reported?

**Comment by ranetto** [comment] 2020-12-15 14:05
Hi James, sorry but I solved:
I realized that in the official keymap you use the action "Pass through key to main window" and then I also inserted it in my custom.
Now everything works ok, it was not osara's fault but my fault.
Thanks always for your availability and sorry if I wasted your time.

**Comment by ScottChesworth** [comment] 2020-12-15 14:21
Hey @leonardder, I'm gonna leave this issue open and assign so you can take a shot at getting chord movement commands to seek. Tbh it's not something we've had any actual user requests for though, so feel free to just close the issue instead if you're not likely to have time.

**Comment by leonardder** [comment] 2020-12-15 14:46
I think it's out of scope for this issue, I will either fix it in a pr or open an ew issue for it.

**Closed by leonardder** 2020-12-15 14:46 UTC
Labels: enhancement, midiEditing, p3
