### ISSUE TITLE
Save Peak Watcher Settings and initialize on Project Open

### ISSUE THREAD

**Issue by ironcross32** [jcsteh/osara#146] opened 2018-03-10 17:25 UTC
It would be handy to be able to configure the peak watcher one time, having the information saved in such a way that when opening reaper subsequently after this first time, the peak watcher is initialized with these settings, and can be immediately used. Then, only when changes need to be made, would it be necessary to enter the peak watcher dialog and reconfigure.

**Comment by jcsteh** [comment] 2019-01-23 12:09
Duplicate of #100.

**Closed by jcsteh** 2019-01-23 12:09 UTC
