### ISSUE TITLE
Bug: odd behaviour when toggling REAPER's generic bypass parameter, unexpected extra key press is required for change to take effect

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#888] opened 2023-03-19 12:08 UTC
Not sure when this started, but using the current snapshot of OSARA (1129), an extra unexpected key press is required when setting REAPER's generic bypass param to "normal" in the FX Parameters dialog. Try this:
1. Instantiate an effect on a track, any effect that makes a clearly audible change in its default state will do.
2. Load the FX Parameters dialog, move to the Bypass parameter third from bottom of the list. Tab to the slider which will be set to "normal" by default. Observe that a single press of UpArrow moves the slider to "bypassed". This is all expected behaviour.
3. Hit DownArrow once, this is where things get weird. The screen reader reports "normal", but examine the internal value and you'll find it's still at 1.0. A second press of DownArrow is required (for which there's no report) to get the internal value back to 0.0.
4. Optionally repeat step 3 with some audio playing for another illustration of the same odd behaviour.

Is this one for us or Cockos? I don't remember anything being changed in the params dialog for a fair while.

**Comment by jcsteh** [comment] 2023-03-24 23:49
The problem is that TrackFX_FormatParamValue returns "normal" for the value 0.5. However, if you set the value 0.5 with TrackFX_SetParam, it gets incorrectly snapped to 1.0. In contrast, if you set the value to 0.499, it gets snapped to 0.0 as expected.

FormatParamValue needs to be consistent with SetParam. It's okay for FormatParamValue 0.5 to return "normal", but in that case, SetParamValue 0.5 should snap to 0.0, not 1.0.

**Comment by jcsteh** [comment] 2023-03-24 23:49
To be clear, this ideally needs to be fixed by Cockos.

**Comment by justinfrankel** [comment] 2023-05-28 22:39
Thanks, fixing TrackFX_FormatParamValue() for the next pre-releases and REAPER v6.81+

**Comment by RDMurray** [comment] 2023-09-06 16:34
This works as expected in 6.82.

**Closed by RDMurray** 2023-09-06 16:34 UTC
Labels: bug, needsReaperFix, paramsDialog, fixRequestedFromCockos
