### ISSUE TITLE
Issue with adjusting volume of a track on Reaper for Mac with Voiceover

### ISSUE THREAD

**Issue by Matthew2244** [jcsteh/osara#921] opened 2023-07-25 23:35 UTC
[Screen Recording 2023-07-25 at 7.32.56 PM.mov.zip](https://github.com/jcsteh/osara/files/12166365/Screen.Recording.2023-07-25.at.7.32.56.PM.mov.zip)
Hello. I am experiencing an issue where the volume of a track can't be adjusted when pressing shift option up and down arrow keys. 
I have done all trouble shooting necessary, and still the issue is happening. I have been experiencing this for about a few months now.

**Comment by TimNoonanVoice** [comment] 2023-07-25 23:45
Can you confirm that SWS is installed and operational? 

Here, the first item in the extensions menu is 'about SWS'.

This volume adjustment is an SWS function. It works perfectly on my M1 Mac.

HTH
Tim


On 26 Jul 2023, at 9:36 am, Matthew2244 ***@***.***> wrote:


Screen Recording 2023-07-25 at 7.32.56 PM.mov.zip <https://github.com/jcsteh/osara/files/12166365/Screen.Recording.2023-07-25.at.7.32.56.PM.mov.zip>
Hello. I am experiencing an issue where the volume of a track can't be adjusted when pressing shift option up and down arrow keys.
I have done all trouble shooting necessary, and still the issue is happening. I have been experiencing this for about a few months now.

**Comment by ScottChesworth** [comment] 2023-07-25 23:45
Think I remember seeing this one on the groups a few months back. Both of the actions that aren't working for you are from SWS, so the first step is to check whether that's installed and running. Go to your menu bar in REAPER, check that you've got an Extensions menu, and if so, check that you've got an About SWS option in there. If not, SWS isn't running right yet.

**Comment by ScottChesworth** [comment] 2023-07-25 23:46
Woo, Tim is speedy!

**Comment by Matthew2244** [comment] 2023-07-25 23:53
I do not see an extentions menu in the menu bar.
Also, hope this reply is getting to you. 😊



From: TimNoonanVoice ***@***.***>
Date: Tuesday, July 25, 2023 at 7:45 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
Can you confirm that SWS is installed and operational?

Here, the first item in the extensions menu is 'about SWS'.

This volume adjustment is an SWS function. It works perfectly on my M1 Mac.

HTH
Tim


On 26 Jul 2023, at 9:36 am, Matthew2244 ***@***.***> wrote:


Screen Recording 2023-07-25 at 7.32.56 PM.mov.zip <https://github.com/jcsteh/osara/files/12166365/Screen.Recording.2023-07-25.at.7.32.56.PM.mov.zip>
Hello. I am experiencing an issue where the volume of a track can't be adjusted when pressing shift option up and down arrow keys.
I have done all trouble shooting necessary, and still the issue is happening. I have been experiencing this for about a few months now.

**Comment by Matthew2244** [comment] 2023-07-26 00:12
I don’t see that in the menu bar.

From: ScottChesworth ***@***.***>
Date: Tuesday, July 25, 2023 at 7:45 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)

Think I remember seeing this one on the groups a few months back. Both of the actions that aren't working for you are from SWS, so the first step is to check whether that's installed and running. Go to your menu bar in REAPER, check that you've got an Extensions menu, and if so, check that you've got an About SWS option in there. If not, SWS isn't running right yet.

**Comment by ScottChesworth** [comment] 2023-07-26 00:17
Gotcha. So as we thought. SWS isn't running yet. If you definitely have it installed, chances are it's either the wrong distribution for your machine, or it hasn't been allowed in System Prefs yet.

**Comment by TimNoonanVoice** [comment] 2023-07-26 00:28
The installation process for SWS is not the same as some others, it usually trips me up initially. As Scott said, make sure you have the matching ARM or intel version for your machine.

Tim




On 26 Jul 2023, at 10:17 am, ScottChesworth ***@***.***> wrote:


Gotcha. So as we thought. SWS isn't running yet. If you definitely have it installed, chances are it's either the wrong distribution for your machine, or it hasn't been allowed in System Prefs yet.

**Comment by Matthew2244** [comment] 2023-07-26 00:31
I have the matching ARM version.

From: TimNoonanVoice ***@***.***>
Date: Tuesday, July 25, 2023 at 8:28 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
The installation process for SWS is not the same as some others, it usually trips me up initially. As Scott said, make sure you have the matching ARM or intel version for your machine.

Tim




On 26 Jul 2023, at 10:17 am, ScottChesworth ***@***.***> wrote:


Gotcha. So as we thought. SWS isn't running yet. If you definitely have it installed, chances are it's either the wrong distribution for your machine, or it hasn't been allowed in System Prefs yet.

**Comment by Matthew2244** [comment] 2023-07-26 00:32
I made sure system settings wasn’t getting angry… lol.
I also did make sure the ARM version was installed.

From: ScottChesworth ***@***.***>
Date: Tuesday, July 25, 2023 at 8:17 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)

Gotcha. So as we thought. SWS isn't running yet. If you definitely have it installed, chances are it's either the wrong distribution for your machine, or it hasn't been allowed in System Prefs yet.

**Comment by TimNoonanVoice** [comment] 2023-07-26 00:58
So,

Did you install SWS by copying the relevant files into the UserPlugins folder? You should have a Grooves folder and some SWS files.

Then, from memory, if you run Reaper, you will get the permissions come up and you need to allow.

Its a while since I've done this, so can only give you a guide.

HTH
Tim


On 26 Jul 2023, at 10:32 am, Matthew2244 ***@***.***> wrote:


I made sure system settings wasn’t getting angry… lol. 
I also did make sure the ARM version was installed. 

From: ScottChesworth ***@***.***> 
Date: Tuesday, July 25, 2023 at 8:17 PM 
To: jcsteh/osara ***@***.***> 
Cc: Matthew2244 ***@***.***>, Author ***@***.***> 
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921) 

Gotcha. So as we thought. SWS isn't running yet. If you definitely have it installed, chances are it's either the wrong distribution for your machine, or it hasn't been allowed in System Prefs yet.

**Comment by Matthew2244** [comment] 2023-07-26 01:04
I have done all there is.

From: TimNoonanVoice ***@***.***>
Date: Tuesday, July 25, 2023 at 8:58 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
So,

Did you install SWS by copying the relevant files into the UserPlugins folder? You should have a Grooves folder and some SWS files.

Then, from memory, if you run Reaper, you will get the permissions come up and you need to allow.

Its a while since I've done this, so can only give you a guide.

HTH
Tim


On 26 Jul 2023, at 10:32 am, Matthew2244 ***@***.***> wrote:


I made sure system settings wasn’t getting angry… lol.
I also did make sure the ARM version was installed.

From: ScottChesworth ***@***.***>
Date: Tuesday, July 25, 2023 at 8:17 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)

Gotcha. So as we thought. SWS isn't running yet. If you definitely have it installed, chances are it's either the wrong distribution for your machine, or it hasn't been allowed in System Prefs yet.

**Comment by jcsteh** [comment] 2023-07-26 01:54
I'm going to close this because it's not a bug in OSARA. However, I don't mind if you want to continue discussing the problem here, as it might be interesting reading for others who come across this.

**Closed by jcsteh** 2023-07-26 01:54 UTC
Labels: invalid

**Comment by Matthew2244** [comment] 2023-07-26 01:56
Totally understand. Is there anything I can do?


From: James Teh ***@***.***>
Date: Tuesday, July 25, 2023 at 9:55 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)

Closed #921<https://github.com/jcsteh/osara/issues/921> as not planned.

**Comment by TimNoonanVoice** [comment] 2023-07-26 02:34
You could try removing the existing files pertaining to SWS, 
downloading the beta version of SWS for ARM, 
copying its files into the UserPlugins folder, 
closing and reopening reaper and seeing if the security message comes up.

Its pretty likely that your Mac is blocking the plugin.

HTH Tim


On 26 Jul 2023, at 11:56 am, Matthew2244 ***@***.***> wrote:


Totally understand. Is there anything I can do? 


From: James Teh ***@***.***> 
Date: Tuesday, July 25, 2023 at 9:55 PM 
To: jcsteh/osara ***@***.***> 
Cc: Matthew2244 ***@***.***>, Author ***@***.***> 
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921) 

Closed #921<https://github.com/jcsteh/osara/issues/921> as not planned.

**Comment by Matthew2244** [comment] 2023-07-26 02:56
I am not getting a dialogue when opening the program back up

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TimNoonanVoice** [comment] 2023-07-26 04:34
Hmm, Running out of ideas here:

1. Make sure the files from the SWS distribution are not in a sub-directory of UserPlugins so the folder grooves should be the only folder in UserPlugins.

2. Double check you are in the correct reaper folder by activating the 
Show REAPER resource path in explorer/finder …
menu choice in the Reaper options menu.

3. Reboot your machine before doing a reinstall of SWS.

4. Watch YouTubes about installing SWS for Mac and see if there are any clues to what might be happening.

Good luck with it.

Tim


 up the SWS 

On 26 Jul 2023, at 12:56 pm, Matthew2244 ***@***.***> wrote:


I am not getting a dialogue when opening the program back up 

Get Outlook for iOS<https://aka.ms/o0ukef> 
________________________________

**Comment by Matthew2244** [comment] 2023-07-26 20:49
Still don’t see extentions in the menu bar.

From: Matthew Whitaker ***@***.***>
Date: Wednesday, July 26, 2023 at 1:02 PM
To: jcsteh/osara ***@***.***>, jcsteh/osara ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
Ok doing this now



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pitermach** [comment] 2023-07-26 21:38
One more thing you can try is using the terminal to remove the quarantine flag. I've encountered the system not prompting me to allow a plugin once, even though it was blocked from running and this was the only way to fix it.

Open the terminal from the utilities folder, then paste the following in and press enter:

xattr -c ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-arm64.dylib

Then try running reaper again and see if the SWS menus show up.

**Comment by Matthew2244** [comment] 2023-07-26 21:41
Didn’t work.



From: pitermach ***@***.***>
Date: Wednesday, July 26, 2023 at 5:38 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
One more thing you can try is using the terminal to remove the quarantine flag. I've encountered the system not prompting me to allow a plugin once, even though it was blocked from running and this was the only way to fix it.

Open the terminal from the utilities folder, then paste the following in and press enter:

xattr -c ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-arm64.dylib

Then try running reaper again and see if the SWS menus show up.

**Comment by Matthew2244** [comment] 2023-07-26 21:42
Would you like to hop on a zoom session or RIM session so we can take a look together? I’m good after 9:00 PM EST tonight and good all day Friday.


From: Matthew Whitaker ***@***.***>
Date: Wednesday, July 26, 2023 at 5:40 PM
To: jcsteh/osara ***@***.***>, jcsteh/osara ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
Didn’t work.



From: pitermach ***@***.***>
Date: Wednesday, July 26, 2023 at 5:38 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
One more thing you can try is using the terminal to remove the quarantine flag. I've encountered the system not prompting me to allow a plugin once, even though it was blocked from running and this was the only way to fix it.

Open the terminal from the utilities folder, then paste the following in and press enter:

xattr -c ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-arm64.dylib

Then try running reaper again and see if the SWS menus show up.

**Comment by ScottChesworth** [comment] 2023-07-26 21:49
Hey this might be something. System Prefs, Security and Privacy, General tab, click the lock to make changes and make sure that "Allow apps downloaded from" is set to "Appstore and identified developers". SWS isn't an identified developer, that's the cause of all this, but I think maybe if you're set to only run apps from the Appstore in there you won't be seeing the security prompts.

**Comment by Matthew2244** [comment] 2023-07-26 22:02
I’m on Ventura. I did check the sequrity settings and made sure all was set correctly.


From: ScottChesworth ***@***.***>
Date: Wednesday, July 26, 2023 at 5:49 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)

Hey this might be something. System Prefs, Security and Privacy, General tab, click the lock to make changes and make sure that "Allow apps downloaded from" is set to "Appstore and identified developers". SWS isn't an identified developer, that's the cause of all this, but I think maybe if you're set to only run apps from the Appstore in there you won't be seeing the security prompts.

**Comment by Matthew2244** [comment] 2023-07-27 02:58
I may need to re-install Mac OS. I’ve tried scripts, installing the SWS beta, checking system settings, etc, and nothing is working.




From: Matthew Whitaker ***@***.***>
Date: Wednesday, July 26, 2023 at 6:02 PM
To: jcsteh/osara ***@***.***>, jcsteh/osara ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)
I’m on Ventura. I did check the sequrity settings and made sure all was set correctly.


From: ScottChesworth ***@***.***>
Date: Wednesday, July 26, 2023 at 5:49 PM
To: jcsteh/osara ***@***.***>
Cc: Matthew2244 ***@***.***>, Author ***@***.***>
Subject: Re: [jcsteh/osara] Issue with adjusting volume of a track on Reaper for Mac with Voiceover (Issue #921)

Hey this might be something. System Prefs, Security and Privacy, General tab, click the lock to make changes and make sure that "Allow apps downloaded from" is set to "Appstore and identified developers". SWS isn't an identified developer, that's the cause of all this, but I think maybe if you're set to only run apps from the Appstore in there you won't be seeing the security prompts.
