### ISSUE TITLE
Would it be possible to have OSARA 0 index parameters for CSI users?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#788] opened 2022-09-07 01:46 UTC
As things stand, REAPER assigns param numbers 0 indexed, whereas OSARA displays 1 indexed in its parameters dialog. I get that 1 indexed is more intuitive to hear, but it's been bought to my attention that it adds extra legwork when making CSI zones. Given the high amount of potential their is for premade CSI zones to provide accessible UX, I said I'd ask whether there's anything that OSARA could do to help the folks who have started mapping and sharing zones.
1. Would switching to 0 indexed params be heavy work to implement?
2. If not, is there any downside to doing it other than a slightly less intuitive count?
3. Again if not, is it perhaps worth an additional config option, so that CSI users can enable the behaviour, and everyone else can have the intuitive count they're already used to?
Thoughts appreciated.

**Comment by jcsteh** [comment] 2022-09-07 02:43
> it's been bought to my attention that it adds extra legwork when making CSI zones.

I'm trying hard not to trivialise here, but subtracting 1 doesn't seem like much legwork. It's not like you have to use a calculator. And I'm guessing you have to get the parameter names manually one by one anyway, so there's already manual process involved. Or is there some technique I'm missing which lets someone get at all the parameter names at once using that dialog?

>     1. Would switching to 0 indexed params be heavy work to implement?

No. I think it's a one line change. OSARA deliberately adds 1 to make it intuitive for users.

>     2. If not, is there any downside to doing it other than a slightly less intuitive count?

No. However, there are more users than there are CSI mappers.

>     3. Again if not, is it perhaps worth an additional config option, so that CSI users can enable the behaviour, and everyone else can have the intuitive count they're already used to?

I don't love the idea of a config option for this. It's easy to add, sure, but "Number parameters from 0 in Parameters dialogs" just seems like such an obscure option.

I'm actually wondering whether the Parameters dialog is the wrong solution entirely for getting parameter numbers for CSI. First, the process is (as I understand it) manual. Second, in plugins like ReaEQ which offer named parameters (band type, etc.), the parameter numbers will be flat out wrong, since named parameters do not have numbers. (In ReaEQ, REAPER param 0 is actually band 1 freq.) Would it be better for someone to write a ReaScript which just dumps all the parameter numbers and names into a text box or something?

**Comment by jcsteh** [comment] 2022-09-07 02:44
Also, how do sighted users do CSI mapping without the Parameters dialog?

**Comment by ScottChesworth** [comment] 2022-09-07 06:36
> how do sighted users do CSI mapping without the Parameters dialog?
> 
The automated way to collect that information is the same whether a user is sighted or not, instantiate the relevant effect, then run a CSI action that dumps param numbers and names into a text file, copy and paste from there to the zone file as needed. I'm not in front of REAPER right now to get the exact action name, searching CSI in the action list will find it.

> I'm trying hard not to trivialise here, but subtracting 1 doesn't seem like much legwork.
> 
I used legwork when perhaps I should've used tediousness. Less tedium with renumbering params would free up more time for writing accompanying help subzones (contextual explainations that can be browsed directly from the surface, kinda like tooltips).

> I don't love the idea of a config option for this. It's easy to add, sure, but "Number parameters from 0 in Parameters dialogs" just seems like such an obscure option.
> 
How about "Number parameters starting from 0 (enable for greater compatibility if making/using CSI zones)"?
We already use that style with "Report transport state (play, record, etc.)".

> in plugins like ReaEQ which offer named parameters (band type, etc.), the parameter numbers will be flat out wrong, since named parameters do not have numbers. (In ReaEQ, REAPER param 0 is actually band 1 freq).
> 
Yeah, there's already been a discussion about that on RWP. I've encouraged that to be moved over here. ReaEQ is an outlier though, no? Is there anywhere else where we're adding named params?

**Comment by davidkreynolds** [comment] 2022-09-07 11:11
I don’t think this is really a problem, and I’ll explain why.

When installing CSI, a number of actions become available, one of which enables the user to write all parameters to a text file preparatory to building a zone file for an effect.

1.Invoke Reaper.

2.press F4, and filter on CSI.

3.Choose the Toggle write parameters to text file.

4.Insert a plugin.

5.Browse to the folder where these text files are stored.

6.there’ll be a [pluginName.txt] file there which will contain every parameter.

Building a zone file just requires matching parameters to buttons/faders.

Best,

 

David.

**Comment by leejul** [comment] 2022-09-07 11:32
Hi,
Parameter order starts with 0 natively in Reaper.
So why we don't have the same result as a sighted person.
In fact, it is manual work.
But we need to go back and forth between the .zon document and the OSARA 
parameters to confirm information during the .zon file creation process.
We must constantly remember that the OSARA parameter numbers are shifted 
by 1.
This increases the risk of user errors, especially if he is a beginner.
In addition, in the case of Native Instruments Kontakt, in the Host 
automation tab, you must ask a sighted person to drag and drop the 
parameters from the library so that they are accessible in the OSARA 
parameters.
Again, OSARA parameters are shifted.
When the parameters are not correctly labeled, we can rename them with 
aliases in Reaper.
We need to confirm with the sighted person if the XYZ parameter is the 
one to be renamed.
The sighted person must always remember to shift by 1 to compare the 
list of parameters in Kontakt versus the list of OSARA parameters.
Again, this increases the risk of user errors.
I've been a CSI user for 4 years and still getting errors caused by this 
problem.
But before working with sighted people in Kontakt, I thought it was 
presented that way in Reaper.
I personally think it's not a good idea to present a list of parameters 
numbered out of step with what a person sees.
I don't think this could be a problem for OSARA users.
I don't see how it could change anything if the parameter list starts 
with 0.
I don't think users memorize parameter numbers.
But maybe there is an important detail that I haven't thought of.

Thanks.

**Comment by jcsteh** [comment] 2022-09-07 11:39
> Hi, Parameter order starts with 0 natively in Reaper. So why we don't have the same result as a sighted person.

Where does a sighted user see the parameter numbers starting with 0? As I understand it, that is an implementation detail in REAPER and isn't displayed visually (except by the CSI write params action). If I'm incorrect about that, then yes, we should match the visual display.

> we need to go back and forth between the .zon document and the OSARA parameters to confirm information

Why are you using OSARA Parameters rather than the CSI write params action?

> In addition, in the case of Native Instruments Kontakt, in the Host automation tab, you must ask a sighted person to drag and drop the parameters from the library so that they are accessible in the OSARA parameters. Again, OSARA parameters are shifted.

Are you saying that a sighted person visually sees 0 based parameter numbers in Kontakt, not just parameter names?

**Comment by leejul** [comment] 2022-09-07 12:05
Making a .zon file seemed simple, yes and no.
If you have for example a Wet parameter.
This can simply be placed on a fader, it's not complicated. This does 
not require additional information.
But if you have a BandType parameters, and this setting gives you 
multiple choices, you need to change the value in the OSARA settings to 
get the actual OSC value, copy that value and paste it into the .zon file.
This procedure must be done for all BandType.
So the line would be as follows:
FXParam 1 (1) [ 0 0.25 0.45 0.60 0.80 0.95 1 ] "BandType"
Each number corresponds to a different BandType.
That's why we need OSARA settings to make a .zon file.
We have to manually change the value of the parameter in order to get 
the real value otherwise, impossible to know which OSC number is 
assigned to which band type.
Yes, sighted people can see the list of automatable parameters in 
Kontakt and it starts with 0.
In addition, OSARA parameters are visible to a sighted person when we 
open the list.

**Comment by ScottChesworth** [comment] 2022-09-07 12:07
> Why are you using OSARA Parameters rather than the CSI write params action?
> 
The CSI action dumps a 0 based list of params, but it can't detect steps. Let's take a commonplace example where a parameter has been exposed as a full range slider, but actually behaves like a switch with 3 positions. To maximize productivity when assigning control of such a parameter to a stepped encoder on the control surface, you'd investigate the slider in the OSARA Params dialog to find the biting points and program those in the zone file. It's this sort of detail that makes it possible for a well-written zone file to feel like you're directly controlling the plug-in. As a comparison, consider the same 3 position switch mapped via NKS, where you'll waste time spinning a knob waiting for something to change. I'm aware that I'm waxing lyrical here, but really, the UX improvement is significant in situ.

> Are you saying that a sighted person visually sees 0 based parameter numbers in Kontakt, not just parameter names?
> 
He's talking about the host automation tab in Kontakt, where it's often possible to manually expose additional params to DAW automation. People have started doing this in shared template resources. And yep, the visual UX displays a 0 based count.

**Comment by jcsteh** [comment] 2022-09-07 12:43
Okay, so I have one (hopefully) final question. It's great that OSARA Parameters allows you to get step values. So how does a sighted user do this? Most sighted users aren't going to be running OSARA.

> Number parameters starting from 0 (enable for greater compatibility if making/using CSI zones)

Ug. It's so specific to CSI though.

> In addition, OSARA parameters are visible to a sighted person when we
open the list.

Yes, but most (all?) sighted users aren't using OSARA. So Kontakt is really the only place you can visually see parameter numbers, unless there's somewhere else in REAPER?

**Comment by leejul** [comment] 2022-09-07 13:03
I don't think it's relevant to try to figure out how a sighted person 
goes about creating a .zon file. The only possibility for us is to use 
the OSARA parameters.
The main thing is that the presentation of the OSARA parameters for the 
numbers does not represent reality and I do not understand the usefulness.
But that's just my opinion.

**Comment by jcsteh** [comment] 2022-09-07 13:23
I think it's relevant because we should ideally be using the right tools for the job. If a sighted user is using some other tool and that's more efficient/effective (but less accessible), we should consider whether that option should be made more accessible somehow. As an example, OSARA Parameters gets dismissed when you switch apps. That's necessary for the purposes of this dialog, but surely not ideal if you're trying to enter data into a zon file.

**Comment by jcsteh** [comment] 2022-09-11 07:01
Anyway, I'm just going to make this change without a setting. It seems I'm outvoted here and I honestly don't feel strongly enough about it to argue. If someone doesn't like it, I disclaim any responsibility. :)

**Closed** 2022-09-11 07:05 UTC
Labels: enhancement, paramsDialog, needInfo

**Comment by leejul** [comment] 2022-09-11 12:47
Thank you James for this change. If there is a user who does not like, I 
can explain to him.
Thanks so much.
