### ISSUE TITLE
OSARA action bug

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#813] opened 2022-11-23 18:09 UTC
Hi,
There is a bug with OSARA action: Cycle automation mode of selected tracks when Report changes made via control surfaces is enabled.
This action is a different automation mode loop and on some mode, NVDA says 0.00 rather than the mode type.
On the other hand, if Report changes made via control surfaces is desabled the behavior is normal.
Thanks.

**Comment by jcsteh** [comment] 2022-11-24 00:29
Duplicate of #802. The only way to fix this is something like #804, but that doesn't work for your use case, so I have no ideas.

**Closed by jcsteh** 2022-11-24 00:29 UTC
