### ISSUE TITLE
Can't navigate left through filtered notes in the midi editor 

### ISSUE THREAD

**Issue by CastleStarter** [jcsteh/osara#463] opened 2021-01-22 20:03 UTC
To reproduce the problem:
Record a series of notes in the midi editor such as an ascending scale. from midi note 60 to 72.
Open filter events dialog with F
Set to display only events that pass filter
Select type of notes
Filter notes from, say, half way up the scale to the top. such as 66 to 72.
Apply selection and press escape to close dialog.
Use right cursor key to move through filtered notes.
Pressing left arrow returns to the start of the item rather than going back through the filtered notes.

Would expect to be able to use left and right arrows to navigate left and right through the filtered notes.

**Comment by leonardder** [comment] 2022-01-24 18:28
This is most likely related to #625. I'm also pretty sure that the steps to reproduce have changed since we started using the binary search iterator. Closing this one, since movement is generally broken anyway and #625 is perfect to monitor that.

**Closed** 2022-01-24 18:48 UTC
