### ISSUE TITLE
signaling when an item is soloed

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#903] opened 2023-05-15 13:20 UTC
Hello, I ask if it can be signaled when an item has been soloed, i.e. I select an item with the usual commands and osara tells me if it is soloed or muted or if it says nothing but only its name it means that that item is normally only selected.
Thank you if you will accept my request.

**Comment by jcsteh** [comment] 2023-05-15 13:47
This is covered in #172. Read that issue for details, but the short story is that the REAPER API didn't previously allow us to get access to this, which is why it wasn't implemented earlier. Apparently it does now, so someone just needs to find the time to work on it.

Closing as a duplicate of #172.

**Closed by jcsteh** 2023-05-15 13:47 UTC
