### ISSUE TITLE
Inserting a new track shouldn't insert inside a closed folder

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#459] opened 2021-01-17 18:04 UTC
1. Create 3 new tracks called "Parent", "First child" and "Last child".
2. Designate "Parent" as a folder, and "Last child" the end of the folder.
3. With the folder open, select Parent, hit Control+T to insert a new track, then hit Control+Shift+Space to report selection. You should find that the new track is reported with its number being accurate, as it's slotted into your tracklist below Parent and above First child. That's expected behaviour and it holds up consistently with the folder state set to either Open or Small. All good.
4. Now delete the new track, close the folder, and repeat the experiment. This time, the report from Control+Shift+Space will be accurate, but if you hit DownArrow, you'll find your new track just hanging out there on its own. The bug is that it shouldn't be visible in the tracklist at this point (at least, it's not visually), because the folder is closed.
5. Hit UpArrow once to move focus back onto the Parent track, then try DownArrowing. At this point, the new child track is no longer reported, and you can find it tucked inside the folder by popping it open. Again, as expected.

Not a huge priority really, but would be good to get it tightened up whenever someone gets time.

**Comment by jcsteh** [comment] 2021-01-17 22:09
When you press control+t, a track is inserted below the current track, even if it's a closed folder. I'd argue this is a REAPER bug: it really should insert a track after the folder, not inside the folder, since the folder is closed.

Regardless, the problem is that when you insert a new track, it gets selected and focused. When you press down arrow, there are no more tracks to visit (since the folder is closed), so OSARA just reports the track you're already on. I guess down arrow could move back up to the previous track, but that feels kinda wrong: you're on track 2 and down arrow moves to track 1. Combine this with the possibility of the folder track being hidden and you get into all sorts of pain: where do you go then?

I refactored the track navigation code a while ago to try to make it more robust and one of the rules I settled on was that if a track is selected and we can't find another track in the requested direction, we should just stay put. Otherwise, things get really nasty, both from a code and UX perspective.

**Comment by jcsteh** [comment] 2021-01-22 02:10
@ScottChesworth, I'm inclined to close this, as OSARA is behaving as expected: namely, it is resorting to the current track if there is no track in the requested direction. However, I'm keen to hear your thoughts from a UX perspective, taking into account what I explained above.

**Comment by ScottChesworth** [comment] 2021-05-22 10:26
I reckon you're right, this is one for Cockos. Gonna leave this open for now just as a reminder to myself if that's ok because I don't think now is the right time to float it (I've already got a queue of stuff for Justin to attend to). Once that cue is cleared, I'll send this in, apply appropriate labels and pop back to close the issue once resolved in Reaper.

**Comment by leonardder** [comment] 2021-11-04 18:51
@ScottChesworth, Just a heads up to ask whether you've been able to send this to the guys at cockos.

**Comment by jcsteh** [comment] 2024-05-06 23:28
This has been fixed in REAPER.

**Closed by jcsteh** 2024-05-06 23:28 UTC
Labels: needsReaperFix, needInfo, p2
