### ISSUE TITLE
With surface feedback enabled and REAPER in any automation mode other than trim/read or write, values returned from the API frequently interrupt our reports and disrupt navigational speech feedback.

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#848] opened 2023-01-26 21:46 UTC
If I display a track envelope and I activate the action OSARA: Toggle Report changes made via control surfaces, the toggle of this action announces the volume of the track once on 2 presses.
When OSARA is supposed to say enabled Report changes made via control surfaces, the track volume value is said instead.

**Comment by ScottChesworth** [comment] 2023-01-26 21:52
I'm not able to reproduce here. Can you give us a step by step sequence to follow? Cheers.

**Comment by leejul** [comment] 2023-01-26 22:57
> I don't understand, I don't have this behavior with my other machines.
I create a track, Ctrl+Alt+V to display the volume envelope and as soon as I toggle the action OSARA: Toggle Report changes made via control surfaces, I have this problem. I have the same problem regardless of the type of envelope.

**Comment by leejul** [comment] 2023-01-26 22:58
### I don't understand, I don't have this behavior with my other machines.
I create a track, Ctrl+Alt+V to display the volume envelope and as soon as I toggle the action OSARA: Toggle Report changes made via control surfaces, I have this problem. I have the same problem regardless of the type of envelope.

**Comment by ScottChesworth** [comment] 2023-01-26 23:35
Hmm, well if it's not happening on your other machines and it's not happening here on mine either, then presumably it's something localized. Have you tried the reaper.ini file from the afflicted machine on a different system where things are reporting as expected? Does the issue move with the ini file? If so, then it's a preference of some kind that's causing it. Try that and let us know the result.

**Comment by leejul** [comment] 2023-01-27 01:14
> Hmm, well if it's not happening on your other machines and it's not happening here on mine either, then presumably it's something localized. Have you tried the reaper.ini file from the afflicted machine on a different system where things are reporting as expected? Does the issue move with the ini file? If so, then it's a preference of some kind that's causing it. Try that and let us know the result.

Ok, vraiment bizarre. j'ai pris le .ini de la machine bugué et je l'ai mis dans une autre machine et je n'ai pas de problème. Par contre, si je prend le .ini de la machine qui n'a pas de bug et que je le met sur la machine bugué, je n'ai plus de problème sur la machine bugué.
Je comprend vraiment pas ce qui pourrait faire ça.

**Comment by ScottChesworth** [comment] 2023-01-27 02:01
That's stranger than Dire Strates doing a double album of Disney covers! Could it be something in reaper-extstate.ini perhaps? Try putting the original reaper.ini file back so you are experiencing the strange behaviour again, then replace reaper-extstate.ini from a machine where the reports are as expected.

**Comment by leejul** [comment] 2023-01-27 02:09
OK, I got it. You don't have this problem because you are in Read/Trim automation mode. If you change the automation mode, you will have the same problem. The problem is so severe that it announces the first point value of any type of envelope even when pressing F4 to open the list of actions. If you activate a volume envelope, OSARA will speak 0.00, a Pan envelope, OSARA will speak Center, etc. Same problem when navigating through the preferences tabs.
All diferent automation modes cause this problem except Read/Trim. Why this mode doesn't bug OSARA but the others do, no idea.

**Comment by leejul** [comment] 2023-01-27 03:24
While trying to solve this problem, I figured out what is wrong with the control surfaces and OSARA.
First, my apologies Jamie for the confusion. In the issue I created, I think it's #804 but I'm not sure because I can't find it, I was telling you that the problem reported by control surface users was solve. Ultimately, it is not settled. Let me explain.
I configured Reaper to be in Read/Trim mode at all times. In this mode, we have no problem of enunciation of value by OSARA randomly.
It is possible to configure Reaper to change the automation mode in different situations.
After recording an automation write pass, automation can automatically switch to a different mode (to avoid overwriting just-written automation). The factory default is Trim/Read Mode.
You also have this option:
Default automation mode:  Drop Down List: Trim/Read, The default automation mode for new tracks. Again, the factory default is Trim/Read Mode.
This last option ensures that as soon as an envelope is activated, the automation mode will be automatically changed to the one selected in this drop-down list.
So that's why I thought the problem was solved.
But here, I'm working on a big CSI update with the X-Touch and I have to make sure everything works in all automation modes. So, I changed Reaper's behavior to always be in Read mode so I could do my tests without having to constantly change the mode manually.
So, since I was in Read mode at all times, I noticed the bugs mentioned above.
As I did not have the same behavior with all automation modes, I thought the problem was solved.
Now that we know that this problem involves all automation modes except Read/Trim and Write, will it be possible for you to locate the cause of the problem?
I don't know if this can help locate the problem of the control surfaces but in any case, again sorry for this confusion.

**Comment by ScottChesworth** [comment] 2023-01-27 09:10
Bingo, can reproduce here now and hooo mamma, that's some disruptive UX. I'm gonna update the issue title, put clearer reproduction steps in the next comment and will assign highest priority. FYI if you examine NVDA's speech buffer, you'll find that reporting is happening as expected, but speech interrupt leads to return values from the API being the last thing spoken instead. It seems like technically everything is doing what it's supposed to do, but the API fires values way more often than is conducive for our use case. This is gonna be tricky to work around. Best I can tell it'll involve rethinking how we're caching surface-related data, it might require some changes to the API. We only have a couple of contributors with a deep enough understanding of REAPER's API and OSARA's architecture to work on this, so please be patient with them while they figure out the best way forward.

**Comment by ScottChesworth** [comment] 2023-01-27 09:23
Reproduction steps:
1. Bind "OSARA: Toggle Report changes made via control surfaces" to a key for easy access, Backspace is free if you're using default key map.
2. Create a new track. Toggle surface feedback a few times to observe it reports as expected. This works fine because by default the automation mode is set to trim/read.
3. Hit Shift+L and choose any automation mode other than Trim/Read or Write. Now when you toggle surface feedback, you'll find surface data interrupts the reports.
4. Hit Shift+L again and move through the list of automation modes, you'll find values interrupt reporting what's selected as you move through the list.
5. Hit F4 for the actions list, try using the search filter, same deal.
Thanks in advance for any time that you can put into smoothing this out. I'm around to persuade Cockos if we need changes from them.

**Comment by ScottChesworth** [comment] 2023-01-27 09:27
Tagging @jcsteh, @RDMurray and @leonardder (our most technical contributors). This idea might be a gross oversimplification, but could this be smoothed over by caching surface data and discarding reports unless the most recent value is different from what was returned prior?

**Comment by jcsteh** [comment] 2023-01-27 10:35
This is effectively a duplicate of #802. As I outlined in https://github.com/jcsteh/osara/issues/802#issuecomment-1355993225, we cannot solve issues like this without selectively ignoring certain surface notifications. I tried to implement this in #804, but we ran into an impasse there, with the strongest viewpoint being that users should just toggle surface feedback on and off on demand to avoid these problems and an unwillingness to consider other options. To be blunt, I am not going to touch this until my question in https://github.com/jcsteh/osara/issues/802#issuecomment-1355993225 is thoroughly addressed concerning the various scenarios and what's expected in those scenarios, not just a solution which doesn't take the various different scenarios into account.

**Closed by jcsteh** 2023-01-27 10:35 UTC
Labels: p1, surfaceFeedback

**Comment by ScottChesworth** [comment] 2023-01-27 11:01
Oops, guess I should've reviewed existing issues before adding to this one. Apologies for the inbox clutter.

**Comment by leejul** [comment] 2023-01-27 17:54
I have no idea if this comment is totally ridiculous but I noticed that if I unplug my audio interface, the problem disappears. Did that little help in locating the problem.

**Comment by ScottChesworth** [comment] 2023-01-27 18:04
It's not that we don't know what causes the problem really, more that we don't have a clear consensus on what to implement as a solution.
That said, it is interesting that this behaves differently without your audio interface connected. I have no idea why that would make a difference!
Does anyone else know why the behaviour changes? Is that potentially a useful thing to investigate?

**Comment by leejul** [comment] 2023-01-27 20:11
It's my mistake, I mixed 2 completely diferent things in the same issue.
    The problem wasn't clear in my head but now that's different.
    My request regarding actions so that users can costomize their workflow and the problem we are currently have about are 2 completely diferent things.
    It was my mistake, I sincerely apologize.
    So, I suggest forgetting about issue #804 for now.
    I can confirm that all users agree on one thing, try to find a solution to fixe the current behavior.
    Until this problem is solved, there is no need to go further in the additional requests concerning the control surfaces.
    Again, sorry Jamie for the confusion.
    Now can we all go ahead and try to find a solution together?

**Comment by leejul** [comment] 2023-02-01 12:59
So, finally, are you interested in further research to locate the source of the problem guys?

**Comment by ScottChesworth** [comment] 2023-02-02 12:39
Sure, interested but probably not able to do much firsthand diagnosis because we don't have X-Touch hardware. Keep us updated with what you find though.

**Comment by Ciceroids** [comment] 2023-02-04 13:26
I have the same problem with my X-Touch as has been described by Lee. I find that the unwanted announcement of automation data is made only where the relative track is in anything other than Read/Trim mode and where that automation has been recorded using X-Touch controls. There is no problem where automation points are manually inserted in Reaper itself.
There are several actions which cause unwanted announcement of automation data, including going to next/previous track, next/previous FX in a track's FX window and even in the Actions list, but simply opening a project with a track in an automation mode other than Read/Trim and turning on Osara's preference to announce control surface changes causes the automation data of the relative track to be spoken. To me, this indicates that either (a) Osara is receiving incorrect events upon such actions or (b) Osara's speaking of automation data is too sensitive and is reacting to irrelevant events. Of course, it may be something else but I would start by looking at why automation values are spoken simply when the Osara preference for announcing control surface changes is turned on.
I am using latest Reaper/Osara/Windows 11.
Paul

**Comment by leejul** [comment] 2023-02-04 14:07
I think The problem is not to know what must be stated or not. 
This issue is considered bad behavior. 
I think we should start by trying to understand why we have this bad behavior in all automation modes except Trim/Read and Read. 
Also, you don't need to have a control surface to cause this problem. Simply activate the report via the control surfaces and change the automation mode of the track to one of the problematic modes.

**Comment by ScottChesworth** [comment] 2023-02-04 14:18
Wow, this thread is hard work.

> I think The problem is not to know what must be stated or not.
> 
How else are we gonna be able to report the information that you do want to hear, and reject the information that you don't need? Remember, the intended purpose of the API we're tapping into is to synchronize changes and feedback between the project and a surface, so of course, it returns frequent updates. If it didn't do that, people would be saying the API was badly behaved, and you'd likely miss out on some information that you do want to hear about.

**Comment by leejul** [comment] 2023-02-04 14:49
I understand, but that doesn't answer the question, why there are 2 automation modes that don't have this bad behavior. When we have the answer to this question, we will be able to analyze the problem as a whole, provide possible solutions, and understand what might not be stated and be stated if we opt for the X Y Z solution. For the moment, we do not don't know what is causing this problem. So how can we know in advance what should or should not be stated?
Useless for the moment to speak about the conclusion whereas we know nothing about the initial problem.
Let's start by knowing what is causing this problem.
Thereafter, with the assessment of the diagnosis and the solutions offered on the table, we will be able to assess the impacts on vocalization.

**Comment by jcsteh** [comment] 2023-02-04 20:59
As I keep telling you, I already tried to solve this in #804. You explicitly rejected that solution saying you would prefer to manually flip control surface feedback on and off. So which is it? Do you want OSARA to try to be smart or do you want to control it yourself? If you want this fixed, something like #804 is
