### ISSUE TITLE
unable to delete envelope points

### ISSUE THREAD

**Issue by Timtam** [jcsteh/osara#310] opened 2020-09-20 20:57 UTC
Hi there,

I have a project here (see below) that has a few envelope points on a track and i'm unable to delete them. @ScottChesworth recommended opening an issue here as its possible that the custom OSARA actions might be the reason behind that.
Steps to reproduce:
* Select second track (Counterpoint)
* Arm envelope (CTRL + L)
* navigate to point 5 onward
* press delete (OSARA will say 0 points removed).
Alternative approaches that also don't work:
* Continuously select all envelope points from point 5 onward with Alt+Shift+right arrow
* delete them with DELETE key - 0 points removed
and:
* create time selection from bar 123 to bar 141
* press Alt+Shift+Delete to delete all envelope points in time selection (0 points removed)
Anything OSARA might have to do with this?

Relevant rpp file: https://www.dropbox.com/s/jvfuj8ied5olpk0/kerubimon-damaged.rpp?dl=1

**Comment by RDMurray** [comment] 2020-09-23 18:46
This is a strange one, but I don't think it is a problem in osara.
- select one of the envelope points
- try to delete it with control+shift+delete (Envelope: Delete all selected points).  Notice that this is a reaper action. Nothing happens.
- Then access the envelope context menu and choose the same command ( delete selected points).  All points disappear, not just the one you selected.

Since this can be reproduced with reaper actions only, it should probably be reported on the Reaper forum.

**Comment by jcsteh** [comment] 2020-10-25 22:47
Closing, since this seems like a REAPER bug unrelated to OSARA.

**Closed by jcsteh** 2020-10-25 22:47 UTC
