### ISSUE TITLE
FR: Make It Possible To Deselect MIDI Notes When Making Selections

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#687] opened 2022-02-18 07:23 UTC
I'm curious to know what you all think.
The Osara actions for moving to previous and next chords and adding to selection are great - due to how they work it's very easy to make note selections in either direction, but there's one thing I'm wondering about.
The problem is, that one can end up pressing shift+left/right more times than intended which results in more notes being selected than desired. Another scenario is that one could simply have the need to shorten his or her note selection a note or two. The only thing one can do in these cases currently is cancel his or her note selection entirely and start from scratch. So the thing I'm wondering about is, wouldn't adding actions for moving to previous and next chords and simultaneously removing them from selection make sense?

**Comment by MatejGolian** [comment] 2022-02-18 07:37
Of course, I meant removing the chords one's moving from from selection.

**Comment by jcsteh** [comment] 2022-02-18 09:41
Duplicate of #475. See discussion there for more details. In short, the way you do this right now is to use noncontiguous selection, but I understand that's not ideal/not intuitive.

**Closed by jcsteh** 2022-02-18 09:41 UTC
