### ISSUE TITLE
Accessing OSARA functions with scripts?

### ISSUE THREAD

**Issue by betov75** [jcsteh/osara#337] opened 2020-10-20 16:21 UTC
Hi! Is there a way I can access the outputMessage() function or something like that within a script (Lua or Python) ? I'm learning C++ but i'm months away of doing something decent with it! :) In short, I want to output text to NVDA and make sure the output don't queue (new output cuts previous output)

Thanks for all

**Comment by ScottChesworth** [comment] 2020-10-20 16:46
There is indeed. I'm not smart enough to know how to use it, but you can see some discussion of limitations around it in #122, and some documentation should already be available within the Reaper API docs if you have OSARA installed. I believe @Timtam implemented support recently as part of his AccessiChords script, perhaps he can chime in here to give you some pointers. His scripts are at https://github.com/timtam/accessichords

**Comment by Timtam** [comment] 2020-10-20 16:54
A function like this one should suffice:
[code]
function speak(text)
  if reaper.osara_outputMessage ~= nil then
    reaper.osara_outputMessage(text)
  end
end
[/code]

This will make sure that the relevant outputMessage function can be found, which might not be the case if the OSARA version currently installed is to old, and if it can be found, it will be called, speaking your text through the currently active screen reader.

**Comment by betov75** [comment] 2020-10-20 17:35
Hi! Thank you very much Toni, that's perfect! I'm working on accessible
control surfaces, do you know if I can receive and send midi information to
controllers using ports etc?? (using script)

Scott: If you, you're not smart enough, I don't have any hope for the human
race! :)

Le mar. 20 oct. 2020 à 12:54, Toni Barth <notifications@github.com> a
écrit :

**Comment by jcsteh** [comment] 2020-10-20 21:44
> In short, I want to output text to NVDA and make sure the output don't queue (new output cuts previous output)

OSARA's outputMessage function can't silence previous speech, though if you issue two messages in quick succession, the first will effectively be ignored. This is unfortunately not a limitation I can fix at the moment.

> I'm working on accessible control surfaces, do you know if I can receive and send midi information to controllers using ports etc??

Respectfully, this is very much off-topic here.

I'm closing this issue, since you already have what you need from OSARA.

**Closed by jcsteh** 2020-10-20 21:44 UTC

**Comment by betov75** [comment] 2020-10-20 22:51
It's maybe off topic. But i'm sincerely despaired. It was not off topic to
me. I won't bother anyone anymore here.

>

**Comment by betov75** [comment] 2020-10-20 23:16
Sorry about that. Thanks for your help.

**Comment by jcsteh** [comment] 2020-10-21 02:23
No problem. For what it's worth, the REAPER forums have areas for scripting and development where I'm sure you'll be able to get answers to your REAPER development questions. Thanks for your understanding.

**Comment by betov75** [comment] 2020-10-22 18:14
Hi James,
I'm very new to the github approach and very excitable, I get into 'couversation mode' ! I'll be very careful not to bother anyone here with off topic stuff again. Thank you very much for your hard work, advice and patience. It's inspiring.

**Comment by ScottChesworth** [comment] 2020-10-22 18:23
You're all good Patrick. Came across in text form a little shorter than it was intended I think is all. Fingers crossed that you can find the pointers you need via the Cockos dev forum. Some serious brains on there man.
